package com.zhihui.order.partner.plateno.service.book;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2016-02-16T14:55:54.337+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://www.7daysinn.cn/booking", name = "BookingSoap")
@XmlSeeAlso({com.zhihui.order.partner.plateno.service.book.sub.ObjectFactory.class, ObjectFactory.class})
public interface BookingSoap {

    /**
     * 预订方法
     */
    @RequestWrapper(localName = "PostBookInfoWithPackage", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.PostBookInfoWithPackage")
    @WebMethod(operationName = "PostBookInfoWithPackage", action = "http://www.7daysinn.cn/booking/PostBookInfoWithPackage")
    @ResponseWrapper(localName = "PostBookInfoWithPackageResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.PostBookInfoWithPackageResponse")
    public void postBookInfoWithPackage(
        @WebParam(name = "sAuth", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sAuth,
        @WebParam(name = "bookingRequest", targetNamespace = "http://www.7daysinn.cn/booking")
        com.zhihui.order.partner.plateno.service.book.CRequestBookingInfo bookingRequest,
        @WebParam(name = "arrPackage", targetNamespace = "http://www.7daysinn.cn/booking")
        com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage arrPackage,
        @WebParam(name = "roomPrice", targetNamespace = "http://www.7daysinn.cn/booking")
        java.math.BigDecimal roomPrice,
        @WebParam(mode = WebParam.Mode.OUT, name = "PostBookInfoWithPackageResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> postBookInfoWithPackageResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "bookResponse", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfDResponseBookingResult> bookResponse
    );

    /**
     * 判断预定是否需要担保或预付--2009-12-10. 0不需要担保  1 需要担保  2需要预付 3不可预定 不检测房态是否满足条件
     */
    @RequestWrapper(localName = "IsBookingAssure", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.IsBookingAssure")
    @WebMethod(operationName = "IsBookingAssure", action = "http://www.7daysinn.cn/booking/IsBookingAssure")
    @ResponseWrapper(localName = "IsBookingAssureResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.IsBookingAssureResponse")
    public void isBookingAssure(
        @WebParam(name = "sAuth", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sAuth,
        @WebParam(name = "sCity", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sCity,
        @WebParam(name = "nHotelId", targetNamespace = "http://www.7daysinn.cn/booking")
        int nHotelId,
        @WebParam(name = "dtBegin", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar dtBegin,
        @WebParam(name = "dtEnd", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar dtEnd,
        @WebParam(name = "sRoomType", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sRoomType,
        @WebParam(name = "nRoomNum", targetNamespace = "http://www.7daysinn.cn/booking")
        int nRoomNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "IsBookingAssureResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> isBookingAssureResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "sMsg", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.String> sMsg
    );

    /**
     * 下单接口，只能下市场活动订单
     */
    @RequestWrapper(localName = "AddMarketOrder", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.AddMarketOrder")
    @WebMethod(operationName = "AddMarketOrder", action = "http://www.7daysinn.cn/booking/AddMarketOrder")
    @ResponseWrapper(localName = "AddMarketOrderResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.AddMarketOrderResponse")
    public void addMarketOrder(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "BookRequest", targetNamespace = "http://www.7daysinn.cn/booking")
        com.zhihui.order.partner.plateno.service.book.RequestBookingInfo bookRequest,
        @WebParam(mode = WebParam.Mode.OUT, name = "AddMarketOrderResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> addMarketOrderResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "BookResponse", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfResponseBookingInfo> bookResponse
    );

    /**
     * 获取远程房态信息fromMongoDB
     */
    @RequestWrapper(localName = "GetForecastRoomStatusFromCache", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetForecastRoomStatusFromCache")
    @WebMethod(operationName = "GetForecastRoomStatusFromCache", action = "http://www.7daysinn.cn/booking/GetForecastRoomStatusFromCache")
    @ResponseWrapper(localName = "GetForecastRoomStatusFromCacheResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetForecastRoomStatusFromCacheResponse")
    public void getForecastRoomStatusFromCache(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "nHotelId", targetNamespace = "http://www.7daysinn.cn/booking")
        int nHotelId,
        @WebParam(name = "dtStartTime", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar dtStartTime,
        @WebParam(name = "dtEndTime", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar dtEndTime,
        @WebParam(name = "sRoomType", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sRoomType,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetForecastRoomStatusFromCacheResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getForecastRoomStatusFromCacheResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "lstForecastRoomStatus", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfDForecastRoomStatus> lstForecastRoomStatus
    );

    /**
     * 根据订单单取预定信息
     */
    @RequestWrapper(localName = "GetOrderNoBookingInfo", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetOrderNoBookingInfo")
    @WebMethod(operationName = "GetOrderNoBookingInfo", action = "http://www.7daysinn.cn/booking/GetOrderNoBookingInfo")
    @ResponseWrapper(localName = "GetOrderNoBookingInfoResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetOrderNoBookingInfoResponse")
    public void getOrderNoBookingInfo(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "sOrderNo", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sOrderNo,
        @WebParam(mode = WebParam.Mode.INOUT, name = "theBookingInfo", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<CTBookingInfo> theBookingInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetOrderNoBookingInfoResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getOrderNoBookingInfoResult
    );

    /**
     * 查询所有市场活动
     */
    @WebResult(name = "GetMarketResult", targetNamespace = "http://www.7daysinn.cn/booking")
    @RequestWrapper(localName = "GetMarket", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetMarket")
    @WebMethod(operationName = "GetMarket", action = "http://www.7daysinn.cn/booking/GetMarket")
    @ResponseWrapper(localName = "GetMarketResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetMarketResponse")
    public com.zhihui.order.partner.plateno.service.book.ArrayOfMarketActInfo getMarket(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication
    );

    /**
     * 查询配额
     */
    @RequestWrapper(localName = "QueryMarketQuota", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.QueryMarketQuota")
    @WebMethod(operationName = "QueryMarketQuota", action = "http://www.7daysinn.cn/booking/QueryMarketQuota")
    @ResponseWrapper(localName = "QueryMarketQuotaResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.QueryMarketQuotaResponse")
    public void queryMarketQuota(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "HotelID", targetNamespace = "http://www.7daysinn.cn/booking")
        int hotelID,
        @WebParam(name = "MarketActID", targetNamespace = "http://www.7daysinn.cn/booking")
        int marketActID,
        @WebParam(name = "BeginDate", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar beginDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Quotas", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfQuota> quotas,
        @WebParam(mode = WebParam.Mode.OUT, name = "QueryMarketQuotaResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> queryMarketQuotaResult
    );

    /**
     * 组合查询，用于查询当天有效夜的订单信息
     */
    @RequestWrapper(localName = "GetBookingInfoByCompose", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetBookingInfoByCompose")
    @WebMethod(operationName = "GetBookingInfoByCompose", action = "http://www.7daysinn.cn/booking/GetBookingInfoByCompose")
    @ResponseWrapper(localName = "GetBookingInfoByComposeResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetBookingInfoByComposeResponse")
    public void getBookingInfoByCompose(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "objCompose", targetNamespace = "http://www.7daysinn.cn/booking")
        com.zhihui.order.partner.plateno.service.book.ComposeSearchInfo objCompose,
        @WebParam(mode = WebParam.Mode.INOUT, name = "arrBookingInfo", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfCTBookingInfo> arrBookingInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetBookingInfoByComposeResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getBookingInfoByComposeResult
    );

    /**
     * 获取账单信息
     */
    @RequestWrapper(localName = "GetAccTranInfo", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetAccTranInfo")
    @WebMethod(operationName = "GetAccTranInfo", action = "http://www.7daysinn.cn/booking/GetAccTranInfo")
    @ResponseWrapper(localName = "GetAccTranInfoResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetAccTranInfoResponse")
    public void getAccTranInfo(
        @WebParam(name = "sOrderNO", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sOrderNO,
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetAccTranInfoResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getAccTranInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "lst", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfAccTrans> lst
    );

    /**
     * 取消预定
     */
    @WebResult(name = "CancelBookingResult", targetNamespace = "http://www.7daysinn.cn/booking")
    @RequestWrapper(localName = "CancelBooking", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.CancelBooking")
    @WebMethod(operationName = "CancelBooking", action = "http://www.7daysinn.cn/booking/CancelBooking")
    @ResponseWrapper(localName = "CancelBookingResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.CancelBookingResponse")
    public int cancelBooking(
        @WebParam(name = "sOrderNo", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sOrderNo,
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication
    );

    /**
     * 查询分店担保状态
     */
    @RequestWrapper(localName = "GetHotelConstraint", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetHotelConstraint")
    @WebMethod(operationName = "GetHotelConstraint", action = "http://www.7daysinn.cn/booking/GetHotelConstraint")
    @ResponseWrapper(localName = "GetHotelConstraintResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetHotelConstraintResponse")
    public void getHotelConstraint(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "nHotelId", targetNamespace = "http://www.7daysinn.cn/booking")
        int nHotelId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "lstEndOfDay", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfDateTime> lstEndOfDay,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetHotelConstraintResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getHotelConstraintResult
    );

    /**
     * 添加账单
     */
    @WebResult(name = "AddAccTranResult", targetNamespace = "http://www.7daysinn.cn/booking")
    @RequestWrapper(localName = "AddAccTran", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.AddAccTran")
    @WebMethod(operationName = "AddAccTran", action = "http://www.7daysinn.cn/booking/AddAccTran")
    @ResponseWrapper(localName = "AddAccTranResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.AddAccTranResponse")
    public int addAccTran(
        @WebParam(name = "sOrderNo", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sOrderNo,
        @WebParam(name = "dAmount", targetNamespace = "http://www.7daysinn.cn/booking")
        java.math.BigDecimal dAmount,
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication
    );

    /**
     * 校验是否可以预定市场活动订单
     */
    @RequestWrapper(localName = "CheckMarketOrderCondition", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.CheckMarketOrderCondition")
    @WebMethod(operationName = "CheckMarketOrderCondition", action = "http://www.7daysinn.cn/booking/CheckMarketOrderCondition")
    @ResponseWrapper(localName = "CheckMarketOrderConditionResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.CheckMarketOrderConditionResponse")
    public void checkMarketOrderCondition(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "Type", targetNamespace = "http://www.7daysinn.cn/booking")
        com.zhihui.order.partner.plateno.service.book.EValidationType type,
        @WebParam(name = "MebCardNo", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String mebCardNo,
        @WebParam(name = "MarketActID", targetNamespace = "http://www.7daysinn.cn/booking")
        int marketActID,
        @WebParam(name = "HotelID", targetNamespace = "http://www.7daysinn.cn/booking")
        int hotelID,
        @WebParam(name = "RoomType", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String roomType,
        @WebParam(name = "BeginDate", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar beginDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(mode = WebParam.Mode.INOUT, name = "ErrorMessage", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "CheckMarketOrderConditionResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Boolean> checkMarketOrderConditionResult
    );

    /**
     * 新预订方法，附含担保金额
     */
    @RequestWrapper(localName = "PostReservationInfoWithPackage", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.PostReservationInfoWithPackage")
    @WebMethod(operationName = "PostReservationInfoWithPackage", action = "http://www.7daysinn.cn/booking/PostReservationInfoWithPackage")
    @ResponseWrapper(localName = "PostReservationInfoWithPackageResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.PostReservationInfoWithPackageResponse")
    public void postReservationInfoWithPackage(
        @WebParam(name = "sAuth", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sAuth,
        @WebParam(name = "bookingRequest", targetNamespace = "http://www.7daysinn.cn/booking")
        com.zhihui.order.partner.plateno.service.book.RequestReservationInfo bookingRequest,
        @WebParam(name = "arrPackage", targetNamespace = "http://www.7daysinn.cn/booking")
        com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage arrPackage,
        @WebParam(name = "roomPrice", targetNamespace = "http://www.7daysinn.cn/booking")
        java.math.BigDecimal roomPrice,
        @WebParam(mode = WebParam.Mode.OUT, name = "PostReservationInfoWithPackageResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> postReservationInfoWithPackageResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "bookResponse", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfDResponseBookingResult> bookResponse
    );

    /**
     * 更改订单为全程担保
     */
    @WebResult(name = "ModifyBookingAssureTypeResult", targetNamespace = "http://www.7daysinn.cn/booking")
    @RequestWrapper(localName = "ModifyBookingAssureType", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.ModifyBookingAssureType")
    @WebMethod(operationName = "ModifyBookingAssureType", action = "http://www.7daysinn.cn/booking/ModifyBookingAssureType")
    @ResponseWrapper(localName = "ModifyBookingAssureTypeResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.ModifyBookingAssureTypeResponse")
    public int modifyBookingAssureType(
        @WebParam(name = "sOrderNo", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sOrderNo,
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication
    );

    /**
     * 获取远程房态信息
     */
    @RequestWrapper(localName = "GetForecastRoomStatus", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetForecastRoomStatus")
    @WebMethod(operationName = "GetForecastRoomStatus", action = "http://www.7daysinn.cn/booking/GetForecastRoomStatus")
    @ResponseWrapper(localName = "GetForecastRoomStatusResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.book.GetForecastRoomStatusResponse")
    public void getForecastRoomStatus(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "nHotelId", targetNamespace = "http://www.7daysinn.cn/booking")
        int nHotelId,
        @WebParam(name = "dtStartTime", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar dtStartTime,
        @WebParam(name = "dtEndTime", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.datatype.XMLGregorianCalendar dtEndTime,
        @WebParam(name = "sRoomType", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sRoomType,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetForecastRoomStatusResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getForecastRoomStatusResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "lstForecastRoomStatus", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfDForecastRoomStatus> lstForecastRoomStatus
    );
}
