
package com.zhihui.order.partner.plateno.service.book;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2016-02-16T14:55:54.143+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class BookingSoap_BookingSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.7daysinn.cn/booking", "Booking");

    private BookingSoap_BookingSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Booking.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Booking ss = new Booking(wsdlURL, SERVICE_NAME);
        BookingSoap port = ss.getBookingSoap12();  
        
        {
        System.out.println("Invoking postBookInfoWithPackage...");
        java.lang.String _postBookInfoWithPackage_sAuth = "_postBookInfoWithPackage_sAuth1502592519";
        com.zhihui.order.partner.plateno.service.book.CRequestBookingInfo _postBookInfoWithPackage_bookingRequest = new com.zhihui.order.partner.plateno.service.book.CRequestBookingInfo();
        _postBookInfoWithPackage_bookingRequest.setRoomCount(542236885);
        _postBookInfoWithPackage_bookingRequest.setDayLength(-1131889491);
        _postBookInfoWithPackage_bookingRequest.setContactor("Contactor1907591798");
        _postBookInfoWithPackage_bookingRequest.setHotelId(105713060);
        _postBookInfoWithPackage_bookingRequest.setOrganId(988720145);
        _postBookInfoWithPackage_bookingRequest.setRoomType("RoomType1618586482");
        _postBookInfoWithPackage_bookingRequest.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.189+08:00"));
        _postBookInfoWithPackage_bookingRequest.setSponsionType(2125937403);
        _postBookInfoWithPackage_bookingRequest.setMobile("Mobile356518938");
        _postBookInfoWithPackage_bookingRequest.setRemark("Remark1348652009");
        com.zhihui.order.partner.plateno.service.book.ArrayOfDecimal _postBookInfoWithPackage_bookingRequestRoomRates = new com.zhihui.order.partner.plateno.service.book.ArrayOfDecimal();
        java.util.List<java.math.BigDecimal> _postBookInfoWithPackage_bookingRequestRoomRatesDecimal = new java.util.ArrayList<java.math.BigDecimal>();
        java.math.BigDecimal _postBookInfoWithPackage_bookingRequestRoomRatesDecimalVal1 = new java.math.BigDecimal("2963541318903702109.4970840785803689281");
        _postBookInfoWithPackage_bookingRequestRoomRatesDecimal.add(_postBookInfoWithPackage_bookingRequestRoomRatesDecimalVal1);
        _postBookInfoWithPackage_bookingRequestRoomRates.getDecimal().addAll(_postBookInfoWithPackage_bookingRequestRoomRatesDecimal);
        _postBookInfoWithPackage_bookingRequest.setRoomRates(_postBookInfoWithPackage_bookingRequestRoomRates);
        com.zhihui.order.partner.plateno.service.book.ArrayOfArrayOfDRequestBookingGuest _postBookInfoWithPackage_bookingRequestEachOrderGuests = new com.zhihui.order.partner.plateno.service.book.ArrayOfArrayOfDRequestBookingGuest();
        java.util.List<com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest> _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest>();
        com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1 = new com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest();
        java.util.List<com.zhihui.order.partner.plateno.service.book.DRequestBookingGuest> _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1DRequestBookingGuest = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.DRequestBookingGuest>();
        _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1.getDRequestBookingGuest().addAll(_postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1DRequestBookingGuest);
        _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest.add(_postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1);
        _postBookInfoWithPackage_bookingRequestEachOrderGuests.getArrayOfDRequestBookingGuest().addAll(_postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest);
        _postBookInfoWithPackage_bookingRequest.setEachOrderGuests(_postBookInfoWithPackage_bookingRequestEachOrderGuests);
        _postBookInfoWithPackage_bookingRequest.setBKMebCardNo("BKMebCardNo1398266079");
        _postBookInfoWithPackage_bookingRequest.setAuthorNumber("AuthorNumber291044597");
        com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage _postBookInfoWithPackage_arrPackage = new com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage();
        java.util.List<com.zhihui.order.partner.plateno.service.book.DConfigPackage> _postBookInfoWithPackage_arrPackageDConfigPackage = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.DConfigPackage>();
        com.zhihui.order.partner.plateno.service.book.DConfigPackage _postBookInfoWithPackage_arrPackageDConfigPackageVal1 = new com.zhihui.order.partner.plateno.service.book.DConfigPackage();
        _postBookInfoWithPackage_arrPackageDConfigPackageVal1.setQuantity(1182856641);
        _postBookInfoWithPackage_arrPackageDConfigPackageVal1.setRate(new java.math.BigDecimal("-1979388837083904867.4015492976392371687"));
        _postBookInfoWithPackage_arrPackageDConfigPackageVal1.setGoodsID(107588815);
        _postBookInfoWithPackage_arrPackageDConfigPackage.add(_postBookInfoWithPackage_arrPackageDConfigPackageVal1);
        _postBookInfoWithPackage_arrPackage.getDConfigPackage().addAll(_postBookInfoWithPackage_arrPackageDConfigPackage);
        java.math.BigDecimal _postBookInfoWithPackage_roomPrice = new java.math.BigDecimal("1079277990972784061.3834462326049276149");
        javax.xml.ws.Holder<java.lang.Integer> _postBookInfoWithPackage_postBookInfoWithPackageResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDResponseBookingResult> _postBookInfoWithPackage_bookResponse = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDResponseBookingResult>();
        port.postBookInfoWithPackage(_postBookInfoWithPackage_sAuth, _postBookInfoWithPackage_bookingRequest, _postBookInfoWithPackage_arrPackage, _postBookInfoWithPackage_roomPrice, _postBookInfoWithPackage_postBookInfoWithPackageResult, _postBookInfoWithPackage_bookResponse);

        System.out.println("postBookInfoWithPackage._postBookInfoWithPackage_postBookInfoWithPackageResult=" + _postBookInfoWithPackage_postBookInfoWithPackageResult.value);
        System.out.println("postBookInfoWithPackage._postBookInfoWithPackage_bookResponse=" + _postBookInfoWithPackage_bookResponse.value);

        }
        {
        System.out.println("Invoking isBookingAssure...");
        java.lang.String _isBookingAssure_sAuth = "_isBookingAssure_sAuth-1994590924";
        java.lang.String _isBookingAssure_sCity = "_isBookingAssure_sCity435709191";
        int _isBookingAssure_nHotelId = -1054296993;
        javax.xml.datatype.XMLGregorianCalendar _isBookingAssure_dtBegin = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.198+08:00");
        javax.xml.datatype.XMLGregorianCalendar _isBookingAssure_dtEnd = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.199+08:00");
        java.lang.String _isBookingAssure_sRoomType = "_isBookingAssure_sRoomType1645205184";
        int _isBookingAssure_nRoomNum = -1041926702;
        javax.xml.ws.Holder<java.lang.Integer> _isBookingAssure_isBookingAssureResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _isBookingAssure_sMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.isBookingAssure(_isBookingAssure_sAuth, _isBookingAssure_sCity, _isBookingAssure_nHotelId, _isBookingAssure_dtBegin, _isBookingAssure_dtEnd, _isBookingAssure_sRoomType, _isBookingAssure_nRoomNum, _isBookingAssure_isBookingAssureResult, _isBookingAssure_sMsg);

        System.out.println("isBookingAssure._isBookingAssure_isBookingAssureResult=" + _isBookingAssure_isBookingAssureResult.value);
        System.out.println("isBookingAssure._isBookingAssure_sMsg=" + _isBookingAssure_sMsg.value);

        }
        {
        System.out.println("Invoking addMarketOrder...");
        java.lang.String _addMarketOrder_authentication = "_addMarketOrder_authentication544879586";
        com.zhihui.order.partner.plateno.service.book.RequestBookingInfo _addMarketOrder_bookRequest = new com.zhihui.order.partner.plateno.service.book.RequestBookingInfo();
        _addMarketOrder_bookRequest.setHotelID(-1994716210);
        _addMarketOrder_bookRequest.setRoomType("RoomType873371333");
        com.zhihui.order.partner.plateno.service.book.ArrayOfRoomRatePerDay _addMarketOrder_bookRequestRoomRates = new com.zhihui.order.partner.plateno.service.book.ArrayOfRoomRatePerDay();
        java.util.List<com.zhihui.order.partner.plateno.service.book.RoomRatePerDay> _addMarketOrder_bookRequestRoomRatesRoomRatePerDay = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.RoomRatePerDay>();
        com.zhihui.order.partner.plateno.service.book.RoomRatePerDay _addMarketOrder_bookRequestRoomRatesRoomRatePerDayVal1 = new com.zhihui.order.partner.plateno.service.book.RoomRatePerDay();
        _addMarketOrder_bookRequestRoomRatesRoomRatePerDayVal1.setRoomRate(new java.math.BigDecimal("-3019043156161696377.3671125010928547374"));
        _addMarketOrder_bookRequestRoomRatesRoomRatePerDayVal1.setEndOfDay(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.200+08:00"));
        _addMarketOrder_bookRequestRoomRatesRoomRatePerDay.add(_addMarketOrder_bookRequestRoomRatesRoomRatePerDayVal1);
        _addMarketOrder_bookRequestRoomRates.getRoomRatePerDay().addAll(_addMarketOrder_bookRequestRoomRatesRoomRatePerDay);
        _addMarketOrder_bookRequest.setRoomRates(_addMarketOrder_bookRequestRoomRates);
        _addMarketOrder_bookRequest.setRoomCount(1287491879);
        _addMarketOrder_bookRequest.setStartDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.201+08:00"));
        _addMarketOrder_bookRequest.setDayLength(424221991);
        _addMarketOrder_bookRequest.setContactor("Contactor-617562549");
        _addMarketOrder_bookRequest.setBKMebCardNo("BKMebCardNo-972406119");
        _addMarketOrder_bookRequest.setMobile("Mobile193064664");
        _addMarketOrder_bookRequest.setMarketActID(234328676);
        _addMarketOrder_bookRequest.setAmount(new java.math.BigDecimal("8012130683952608199.837459209258995454"));
        com.zhihui.order.partner.plateno.service.book.ArrayOfGuestInfo _addMarketOrder_bookRequestGuests = new com.zhihui.order.partner.plateno.service.book.ArrayOfGuestInfo();
        java.util.List<com.zhihui.order.partner.plateno.service.book.GuestInfo> _addMarketOrder_bookRequestGuestsGuestInfo = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.GuestInfo>();
        com.zhihui.order.partner.plateno.service.book.GuestInfo _addMarketOrder_bookRequestGuestsGuestInfoVal1 = new com.zhihui.order.partner.plateno.service.book.GuestInfo();
        _addMarketOrder_bookRequestGuestsGuestInfoVal1.setName("Name1210550670");
        _addMarketOrder_bookRequestGuestsGuestInfoVal1.setMobile("Mobile1737417838");
        _addMarketOrder_bookRequestGuestsGuestInfoVal1.setRemark("Remark-1350177187");
        _addMarketOrder_bookRequestGuestsGuestInfo.add(_addMarketOrder_bookRequestGuestsGuestInfoVal1);
        _addMarketOrder_bookRequestGuests.getGuestInfo().addAll(_addMarketOrder_bookRequestGuestsGuestInfo);
        _addMarketOrder_bookRequest.setGuests(_addMarketOrder_bookRequestGuests);
        _addMarketOrder_bookRequest.setRemark("Remark-1321891874");
        javax.xml.ws.Holder<java.lang.Integer> _addMarketOrder_addMarketOrderResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfResponseBookingInfo> _addMarketOrder_bookResponse = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfResponseBookingInfo>();
        port.addMarketOrder(_addMarketOrder_authentication, _addMarketOrder_bookRequest, _addMarketOrder_addMarketOrderResult, _addMarketOrder_bookResponse);

        System.out.println("addMarketOrder._addMarketOrder_addMarketOrderResult=" + _addMarketOrder_addMarketOrderResult.value);
        System.out.println("addMarketOrder._addMarketOrder_bookResponse=" + _addMarketOrder_bookResponse.value);

        }
        {
        System.out.println("Invoking getForecastRoomStatusFromCache...");
        java.lang.String _getForecastRoomStatusFromCache_authentication = "_getForecastRoomStatusFromCache_authentication-665251683";
        int _getForecastRoomStatusFromCache_nHotelId = 1467040844;
        javax.xml.datatype.XMLGregorianCalendar _getForecastRoomStatusFromCache_dtStartTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.204+08:00");
        javax.xml.datatype.XMLGregorianCalendar _getForecastRoomStatusFromCache_dtEndTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.204+08:00");
        java.lang.String _getForecastRoomStatusFromCache_sRoomType = "_getForecastRoomStatusFromCache_sRoomType1343302761";
        javax.xml.ws.Holder<java.lang.Integer> _getForecastRoomStatusFromCache_getForecastRoomStatusFromCacheResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDForecastRoomStatus> _getForecastRoomStatusFromCache_lstForecastRoomStatus = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDForecastRoomStatus>();
        port.getForecastRoomStatusFromCache(_getForecastRoomStatusFromCache_authentication, _getForecastRoomStatusFromCache_nHotelId, _getForecastRoomStatusFromCache_dtStartTime, _getForecastRoomStatusFromCache_dtEndTime, _getForecastRoomStatusFromCache_sRoomType, _getForecastRoomStatusFromCache_getForecastRoomStatusFromCacheResult, _getForecastRoomStatusFromCache_lstForecastRoomStatus);

        System.out.println("getForecastRoomStatusFromCache._getForecastRoomStatusFromCache_getForecastRoomStatusFromCacheResult=" + _getForecastRoomStatusFromCache_getForecastRoomStatusFromCacheResult.value);
        System.out.println("getForecastRoomStatusFromCache._getForecastRoomStatusFromCache_lstForecastRoomStatus=" + _getForecastRoomStatusFromCache_lstForecastRoomStatus.value);

        }
        {
        System.out.println("Invoking getOrderNoBookingInfo...");
        java.lang.String _getOrderNoBookingInfo_authentication = "_getOrderNoBookingInfo_authentication2034246430";
        java.lang.String _getOrderNoBookingInfo_sOrderNo = "_getOrderNoBookingInfo_sOrderNo-1932953347";
        com.zhihui.order.partner.plateno.service.book.CTBookingInfo _getOrderNoBookingInfo_theBookingInfoVal = new com.zhihui.order.partner.plateno.service.book.CTBookingInfo();
        _getOrderNoBookingInfo_theBookingInfoVal.setRefund(new java.math.BigDecimal("-5564593717144003341.6317479727602965754"));
        _getOrderNoBookingInfo_theBookingInfoVal.setAmout(new java.math.BigDecimal("-3005353325269701187.1183239268845818530"));
        _getOrderNoBookingInfo_theBookingInfoVal.setNAssureType(-1509488931);
        _getOrderNoBookingInfo_theBookingInfoVal.setSSellerID("SSellerID487201281");
        _getOrderNoBookingInfo_theBookingInfoVal.setSRoomNo("SRoomNo-1082119825");
        _getOrderNoBookingInfo_theBookingInfoVal.setSOrderNo("SOrderNo-924389839");
        _getOrderNoBookingInfo_theBookingInfoVal.setNOrderSubID(-473426810);
        _getOrderNoBookingInfo_theBookingInfoVal.setNHotelID(1054694909);
        _getOrderNoBookingInfo_theBookingInfoVal.setNRoomTypeID(-763437881);
        _getOrderNoBookingInfo_theBookingInfoVal.setCdArrival(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.207+08:00"));
        _getOrderNoBookingInfo_theBookingInfoVal.setCdDepart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.207+08:00"));
        com.zhihui.order.partner.plateno.service.book.CTStatusType _getOrderNoBookingInfo_theBookingInfoValNStatus = com.zhihui.order.partner.plateno.service.book.CTStatusType.LEAVE;
        _getOrderNoBookingInfo_theBookingInfoVal.setNStatus(_getOrderNoBookingInfo_theBookingInfoValNStatus);
        _getOrderNoBookingInfo_theBookingInfoVal.setNOrigin("NOrigin-1388571670");
        _getOrderNoBookingInfo_theBookingInfoVal.setCdBookedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.208+08:00"));
        _getOrderNoBookingInfo_theBookingInfoVal.setNBookMebID(-1268670799);
        _getOrderNoBookingInfo_theBookingInfoVal.setNBookPropertyID(52687180);
        _getOrderNoBookingInfo_theBookingInfoVal.setSBookGstName("SBookGstName854430732");
        _getOrderNoBookingInfo_theBookingInfoVal.setSBookGstMoble("SBookGstMoble532049058");
        _getOrderNoBookingInfo_theBookingInfoVal.setSChkinGstName("SChkinGstName1543981542");
        _getOrderNoBookingInfo_theBookingInfoVal.setSChkinGstMobile("SChkinGstMobile-1531416787");
        _getOrderNoBookingInfo_theBookingInfoVal.setSHotelName("SHotelName1665561836");
        _getOrderNoBookingInfo_theBookingInfoVal.setSRoomType("SRoomType-1500459809");
        _getOrderNoBookingInfo_theBookingInfoVal.setSRemarks("SRemarks-1351880078");
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.CTBookingInfo> _getOrderNoBookingInfo_theBookingInfo = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.CTBookingInfo>(_getOrderNoBookingInfo_theBookingInfoVal);
        javax.xml.ws.Holder<java.lang.Integer> _getOrderNoBookingInfo_getOrderNoBookingInfoResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getOrderNoBookingInfo(_getOrderNoBookingInfo_authentication, _getOrderNoBookingInfo_sOrderNo, _getOrderNoBookingInfo_theBookingInfo, _getOrderNoBookingInfo_getOrderNoBookingInfoResult);

        System.out.println("getOrderNoBookingInfo._getOrderNoBookingInfo_theBookingInfo=" + _getOrderNoBookingInfo_theBookingInfo.value);
        System.out.println("getOrderNoBookingInfo._getOrderNoBookingInfo_getOrderNoBookingInfoResult=" + _getOrderNoBookingInfo_getOrderNoBookingInfoResult.value);

        }
        {
        System.out.println("Invoking getMarket...");
        java.lang.String _getMarket_authentication = "_getMarket_authentication-1294850480";
        com.zhihui.order.partner.plateno.service.book.ArrayOfMarketActInfo _getMarket__return = port.getMarket(_getMarket_authentication);
        System.out.println("getMarket.result=" + _getMarket__return);


        }
        {
        System.out.println("Invoking queryMarketQuota...");
        java.lang.String _queryMarketQuota_authentication = "_queryMarketQuota_authentication-1456326547";
        int _queryMarketQuota_hotelID = 1915221369;
        int _queryMarketQuota_marketActID = 113716410;
        javax.xml.datatype.XMLGregorianCalendar _queryMarketQuota_beginDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.211+08:00");
        javax.xml.datatype.XMLGregorianCalendar _queryMarketQuota_endDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.211+08:00");
        com.zhihui.order.partner.plateno.service.book.ArrayOfQuota _queryMarketQuota_quotasVal = new com.zhihui.order.partner.plateno.service.book.ArrayOfQuota();
        java.util.List<com.zhihui.order.partner.plateno.service.book.Quota> _queryMarketQuota_quotasValQuota = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.Quota>();
        com.zhihui.order.partner.plateno.service.book.Quota _queryMarketQuota_quotasValQuotaVal1 = new com.zhihui.order.partner.plateno.service.book.Quota();
        _queryMarketQuota_quotasValQuotaVal1.setHotelID(377236102);
        _queryMarketQuota_quotasValQuotaVal1.setRoomType("RoomType-433441959");
        _queryMarketQuota_quotasValQuotaVal1.setRoomTypeName("RoomTypeName-1915702457");
        _queryMarketQuota_quotasValQuotaVal1.setMebRoomRate(new java.math.BigDecimal("-4924071051057537280.2763690139934955952"));
        _queryMarketQuota_quotasValQuotaVal1.setDiscountRoomRate(new java.math.BigDecimal("5913856048009954562.7118423596115645058"));
        _queryMarketQuota_quotasValQuotaVal1.setMarketActID(-263579845);
        _queryMarketQuota_quotasValQuotaVal1.setCanBookFlag(true);
        _queryMarketQuota_quotasValQuotaVal1.setEndOfDay(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.212+08:00"));
        _queryMarketQuota_quotasValQuota.add(_queryMarketQuota_quotasValQuotaVal1);
        _queryMarketQuota_quotasVal.getQuota().addAll(_queryMarketQuota_quotasValQuota);
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfQuota> _queryMarketQuota_quotas = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfQuota>(_queryMarketQuota_quotasVal);
        javax.xml.ws.Holder<java.lang.Integer> _queryMarketQuota_queryMarketQuotaResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.queryMarketQuota(_queryMarketQuota_authentication, _queryMarketQuota_hotelID, _queryMarketQuota_marketActID, _queryMarketQuota_beginDate, _queryMarketQuota_endDate, _queryMarketQuota_quotas, _queryMarketQuota_queryMarketQuotaResult);

        System.out.println("queryMarketQuota._queryMarketQuota_quotas=" + _queryMarketQuota_quotas.value);
        System.out.println("queryMarketQuota._queryMarketQuota_queryMarketQuotaResult=" + _queryMarketQuota_queryMarketQuotaResult.value);

        }
        {
        System.out.println("Invoking getBookingInfoByCompose...");
        java.lang.String _getBookingInfoByCompose_authentication = "_getBookingInfoByCompose_authentication1155905665";
        com.zhihui.order.partner.plateno.service.book.ComposeSearchInfo _getBookingInfoByCompose_objCompose = new com.zhihui.order.partner.plateno.service.book.ComposeSearchInfo();
        _getBookingInfoByCompose_objCompose.setSearchTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.214+08:00"));
        com.zhihui.order.partner.plateno.service.book.CTStatusType _getBookingInfoByCompose_objComposeStatus = com.zhihui.order.partner.plateno.service.book.CTStatusType.ALL;
        _getBookingInfoByCompose_objCompose.setStatus(_getBookingInfoByCompose_objComposeStatus);
        _getBookingInfoByCompose_objCompose.setCompose(true);
        com.zhihui.order.partner.plateno.service.book.ArrayOfCTBookingInfo _getBookingInfoByCompose_arrBookingInfoVal = new com.zhihui.order.partner.plateno.service.book.ArrayOfCTBookingInfo();
        java.util.List<com.zhihui.order.partner.plateno.service.book.CTBookingInfo> _getBookingInfoByCompose_arrBookingInfoValCTBookingInfo = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.CTBookingInfo>();
        com.zhihui.order.partner.plateno.service.book.CTBookingInfo _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1 = new com.zhihui.order.partner.plateno.service.book.CTBookingInfo();
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setRefund(new java.math.BigDecimal("1147239236579297093.2322689440080578828"));
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setAmout(new java.math.BigDecimal("8690064626770235858.8221799704349417602"));
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNAssureType(320105118);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSSellerID("SSellerID138620900");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSRoomNo("SRoomNo1039716626");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSOrderNo("SOrderNo-1203889117");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNOrderSubID(-58474859);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNHotelID(841278943);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNRoomTypeID(-662087107);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setCdArrival(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.215+08:00"));
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setCdDepart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.216+08:00"));
        com.zhihui.order.partner.plateno.service.book.CTStatusType _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1NStatus = com.zhihui.order.partner.plateno.service.book.CTStatusType.NO_SHOW;
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNStatus(_getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1NStatus);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNOrigin("NOrigin616416287");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setCdBookedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.216+08:00"));
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNBookMebID(-1430986512);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNBookPropertyID(1812439755);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSBookGstName("SBookGstName-61040373");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSBookGstMoble("SBookGstMoble-972086347");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSChkinGstName("SChkinGstName-378547853");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSChkinGstMobile("SChkinGstMobile-1477112449");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSHotelName("SHotelName1992772511");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSRoomType("SRoomType-1895010683");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSRemarks("SRemarks-1170176108");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfo.add(_getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1);
        _getBookingInfoByCompose_arrBookingInfoVal.getCTBookingInfo().addAll(_getBookingInfoByCompose_arrBookingInfoValCTBookingInfo);
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfCTBookingInfo> _getBookingInfoByCompose_arrBookingInfo = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfCTBookingInfo>(_getBookingInfoByCompose_arrBookingInfoVal);
        javax.xml.ws.Holder<java.lang.Integer> _getBookingInfoByCompose_getBookingInfoByComposeResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getBookingInfoByCompose(_getBookingInfoByCompose_authentication, _getBookingInfoByCompose_objCompose, _getBookingInfoByCompose_arrBookingInfo, _getBookingInfoByCompose_getBookingInfoByComposeResult);

        System.out.println("getBookingInfoByCompose._getBookingInfoByCompose_arrBookingInfo=" + _getBookingInfoByCompose_arrBookingInfo.value);
        System.out.println("getBookingInfoByCompose._getBookingInfoByCompose_getBookingInfoByComposeResult=" + _getBookingInfoByCompose_getBookingInfoByComposeResult.value);

        }
        {
        System.out.println("Invoking getAccTranInfo...");
        java.lang.String _getAccTranInfo_sOrderNO = "_getAccTranInfo_sOrderNO144731934";
        java.lang.String _getAccTranInfo_authentication = "_getAccTranInfo_authentication-1870522060";
        javax.xml.ws.Holder<java.lang.Integer> _getAccTranInfo_getAccTranInfoResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfAccTrans> _getAccTranInfo_lst = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfAccTrans>();
        port.getAccTranInfo(_getAccTranInfo_sOrderNO, _getAccTranInfo_authentication, _getAccTranInfo_getAccTranInfoResult, _getAccTranInfo_lst);

        System.out.println("getAccTranInfo._getAccTranInfo_getAccTranInfoResult=" + _getAccTranInfo_getAccTranInfoResult.value);
        System.out.println("getAccTranInfo._getAccTranInfo_lst=" + _getAccTranInfo_lst.value);

        }
        {
        System.out.println("Invoking cancelBooking...");
        java.lang.String _cancelBooking_sOrderNo = "_cancelBooking_sOrderNo-1476776349";
        java.lang.String _cancelBooking_authentication = "_cancelBooking_authentication1444148792";
        int _cancelBooking__return = port.cancelBooking(_cancelBooking_sOrderNo, _cancelBooking_authentication);
        System.out.println("cancelBooking.result=" + _cancelBooking__return);


        }
        {
        System.out.println("Invoking getHotelConstraint...");
        java.lang.String _getHotelConstraint_authentication = "_getHotelConstraint_authentication-1426841208";
        int _getHotelConstraint_nHotelId = -1241577429;
        com.zhihui.order.partner.plateno.service.book.ArrayOfDateTime _getHotelConstraint_lstEndOfDayVal = new com.zhihui.order.partner.plateno.service.book.ArrayOfDateTime();
        java.util.List<javax.xml.datatype.XMLGregorianCalendar> _getHotelConstraint_lstEndOfDayValDateTime = new java.util.ArrayList<javax.xml.datatype.XMLGregorianCalendar>();
        javax.xml.datatype.XMLGregorianCalendar _getHotelConstraint_lstEndOfDayValDateTimeVal1 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.220+08:00");
        _getHotelConstraint_lstEndOfDayValDateTime.add(_getHotelConstraint_lstEndOfDayValDateTimeVal1);
        _getHotelConstraint_lstEndOfDayVal.getDateTime().addAll(_getHotelConstraint_lstEndOfDayValDateTime);
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDateTime> _getHotelConstraint_lstEndOfDay = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDateTime>(_getHotelConstraint_lstEndOfDayVal);
        javax.xml.ws.Holder<java.lang.Integer> _getHotelConstraint_getHotelConstraintResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getHotelConstraint(_getHotelConstraint_authentication, _getHotelConstraint_nHotelId, _getHotelConstraint_lstEndOfDay, _getHotelConstraint_getHotelConstraintResult);

        System.out.println("getHotelConstraint._getHotelConstraint_lstEndOfDay=" + _getHotelConstraint_lstEndOfDay.value);
        System.out.println("getHotelConstraint._getHotelConstraint_getHotelConstraintResult=" + _getHotelConstraint_getHotelConstraintResult.value);

        }
        {
        System.out.println("Invoking addAccTran...");
        java.lang.String _addAccTran_sOrderNo = "_addAccTran_sOrderNo-695107327";
        java.math.BigDecimal _addAccTran_dAmount = new java.math.BigDecimal("7849774276833555469.8277328143244152226");
        java.lang.String _addAccTran_authentication = "_addAccTran_authentication1170699071";
        int _addAccTran__return = port.addAccTran(_addAccTran_sOrderNo, _addAccTran_dAmount, _addAccTran_authentication);
        System.out.println("addAccTran.result=" + _addAccTran__return);


        }
        {
        System.out.println("Invoking checkMarketOrderCondition...");
        java.lang.String _checkMarketOrderCondition_authentication = "_checkMarketOrderCondition_authentication1452788985";
        com.zhihui.order.partner.plateno.service.book.EValidationType _checkMarketOrderCondition_type = com.zhihui.order.partner.plateno.service.book.EValidationType.IS_CAN_BOOK;
        java.lang.String _checkMarketOrderCondition_mebCardNo = "_checkMarketOrderCondition_mebCardNo-82146692";
        int _checkMarketOrderCondition_marketActID = 923260541;
        int _checkMarketOrderCondition_hotelID = 1090785392;
        java.lang.String _checkMarketOrderCondition_roomType = "_checkMarketOrderCondition_roomType152713912";
        javax.xml.datatype.XMLGregorianCalendar _checkMarketOrderCondition_beginDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.222+08:00");
        javax.xml.datatype.XMLGregorianCalendar _checkMarketOrderCondition_endDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.223+08:00");
        java.lang.String _checkMarketOrderCondition_errorMessageVal = "_checkMarketOrderCondition_errorMessageVal-1131003307";
        javax.xml.ws.Holder<java.lang.String> _checkMarketOrderCondition_errorMessage = new javax.xml.ws.Holder<java.lang.String>(_checkMarketOrderCondition_errorMessageVal);
        javax.xml.ws.Holder<java.lang.Boolean> _checkMarketOrderCondition_checkMarketOrderConditionResult = new javax.xml.ws.Holder<java.lang.Boolean>();
        port.checkMarketOrderCondition(_checkMarketOrderCondition_authentication, _checkMarketOrderCondition_type, _checkMarketOrderCondition_mebCardNo, _checkMarketOrderCondition_marketActID, _checkMarketOrderCondition_hotelID, _checkMarketOrderCondition_roomType, _checkMarketOrderCondition_beginDate, _checkMarketOrderCondition_endDate, _checkMarketOrderCondition_errorMessage, _checkMarketOrderCondition_checkMarketOrderConditionResult);

        System.out.println("checkMarketOrderCondition._checkMarketOrderCondition_errorMessage=" + _checkMarketOrderCondition_errorMessage.value);
        System.out.println("checkMarketOrderCondition._checkMarketOrderCondition_checkMarketOrderConditionResult=" + _checkMarketOrderCondition_checkMarketOrderConditionResult.value);

        }
        {
        System.out.println("Invoking postReservationInfoWithPackage...");
        java.lang.String _postReservationInfoWithPackage_sAuth = "_postReservationInfoWithPackage_sAuth-612110980";
        com.zhihui.order.partner.plateno.service.book.RequestReservationInfo _postReservationInfoWithPackage_bookingRequest = new com.zhihui.order.partner.plateno.service.book.RequestReservationInfo();
        _postReservationInfoWithPackage_bookingRequest.setAmout(new java.math.BigDecimal("4479991465890293004.8746742476738914613"));
        _postReservationInfoWithPackage_bookingRequest.setRoomCount(-522843532);
        _postReservationInfoWithPackage_bookingRequest.setDayLength(1079478773);
        _postReservationInfoWithPackage_bookingRequest.setContactor("Contactor132094574");
        _postReservationInfoWithPackage_bookingRequest.setHotelId(504621128);
        _postReservationInfoWithPackage_bookingRequest.setOrganId(1491711334);
        _postReservationInfoWithPackage_bookingRequest.setRoomType("RoomType-1312749785");
        _postReservationInfoWithPackage_bookingRequest.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.225+08:00"));
        _postReservationInfoWithPackage_bookingRequest.setMobile("Mobile-2081852535");
        _postReservationInfoWithPackage_bookingRequest.setRemark("Remark411479489");
        com.zhihui.order.partner.plateno.service.book.ArrayOfDecimal _postReservationInfoWithPackage_bookingRequestRoomRates = new com.zhihui.order.partner.plateno.service.book.ArrayOfDecimal();
        java.util.List<java.math.BigDecimal> _postReservationInfoWithPackage_bookingRequestRoomRatesDecimal = new java.util.ArrayList<java.math.BigDecimal>();
        java.math.BigDecimal _postReservationInfoWithPackage_bookingRequestRoomRatesDecimalVal1 = new java.math.BigDecimal("5339622193468952886.380876598472954402");
        _postReservationInfoWithPackage_bookingRequestRoomRatesDecimal.add(_postReservationInfoWithPackage_bookingRequestRoomRatesDecimalVal1);
        _postReservationInfoWithPackage_bookingRequestRoomRates.getDecimal().addAll(_postReservationInfoWithPackage_bookingRequestRoomRatesDecimal);
        _postReservationInfoWithPackage_bookingRequest.setRoomRates(_postReservationInfoWithPackage_bookingRequestRoomRates);
        com.zhihui.order.partner.plateno.service.book.ArrayOfArrayOfDRequestBookingGuest _postReservationInfoWithPackage_bookingRequestEachOrderGuests = new com.zhihui.order.partner.plateno.service.book.ArrayOfArrayOfDRequestBookingGuest();
        java.util.List<com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest> _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest>();
        com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1 = new com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest();
        java.util.List<com.zhihui.order.partner.plateno.service.book.DRequestBookingGuest> _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1DRequestBookingGuest = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.DRequestBookingGuest>();
        _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1.getDRequestBookingGuest().addAll(_postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1DRequestBookingGuest);
        _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest.add(_postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1);
        _postReservationInfoWithPackage_bookingRequestEachOrderGuests.getArrayOfDRequestBookingGuest().addAll(_postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest);
        _postReservationInfoWithPackage_bookingRequest.setEachOrderGuests(_postReservationInfoWithPackage_bookingRequestEachOrderGuests);
        _postReservationInfoWithPackage_bookingRequest.setBKMebCardNo("BKMebCardNo297708547");
        _postReservationInfoWithPackage_bookingRequest.setAuthorNumber("AuthorNumber1712479508");
        _postReservationInfoWithPackage_bookingRequest.setRatePlanCategory(1107930605);
        com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage _postReservationInfoWithPackage_arrPackage = new com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage();
        java.util.List<com.zhihui.order.partner.plateno.service.book.DConfigPackage> _postReservationInfoWithPackage_arrPackageDConfigPackage = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.DConfigPackage>();
        com.zhihui.order.partner.plateno.service.book.DConfigPackage _postReservationInfoWithPackage_arrPackageDConfigPackageVal1 = new com.zhihui.order.partner.plateno.service.book.DConfigPackage();
        _postReservationInfoWithPackage_arrPackageDConfigPackageVal1.setQuantity(233134397);
        _postReservationInfoWithPackage_arrPackageDConfigPackageVal1.setRate(new java.math.BigDecimal("966386803886530008.3980458764180338722"));
        _postReservationInfoWithPackage_arrPackageDConfigPackageVal1.setGoodsID(1858665028);
        _postReservationInfoWithPackage_arrPackageDConfigPackage.add(_postReservationInfoWithPackage_arrPackageDConfigPackageVal1);
        _postReservationInfoWithPackage_arrPackage.getDConfigPackage().addAll(_postReservationInfoWithPackage_arrPackageDConfigPackage);
        java.math.BigDecimal _postReservationInfoWithPackage_roomPrice = new java.math.BigDecimal("1991957452240660976.8225025100823101024");
        javax.xml.ws.Holder<java.lang.Integer> _postReservationInfoWithPackage_postReservationInfoWithPackageResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDResponseBookingResult> _postReservationInfoWithPackage_bookResponse = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDResponseBookingResult>();
        port.postReservationInfoWithPackage(_postReservationInfoWithPackage_sAuth, _postReservationInfoWithPackage_bookingRequest, _postReservationInfoWithPackage_arrPackage, _postReservationInfoWithPackage_roomPrice, _postReservationInfoWithPackage_postReservationInfoWithPackageResult, _postReservationInfoWithPackage_bookResponse);

        System.out.println("postReservationInfoWithPackage._postReservationInfoWithPackage_postReservationInfoWithPackageResult=" + _postReservationInfoWithPackage_postReservationInfoWithPackageResult.value);
        System.out.println("postReservationInfoWithPackage._postReservationInfoWithPackage_bookResponse=" + _postReservationInfoWithPackage_bookResponse.value);

        }
        {
        System.out.println("Invoking modifyBookingAssureType...");
        java.lang.String _modifyBookingAssureType_sOrderNo = "_modifyBookingAssureType_sOrderNo2044682617";
        java.lang.String _modifyBookingAssureType_authentication = "_modifyBookingAssureType_authentication2125961016";
        int _modifyBookingAssureType__return = port.modifyBookingAssureType(_modifyBookingAssureType_sOrderNo, _modifyBookingAssureType_authentication);
        System.out.println("modifyBookingAssureType.result=" + _modifyBookingAssureType__return);


        }
        {
        System.out.println("Invoking getForecastRoomStatus...");
        java.lang.String _getForecastRoomStatus_authentication = "_getForecastRoomStatus_authentication-1047590964";
        int _getForecastRoomStatus_nHotelId = -144963029;
        javax.xml.datatype.XMLGregorianCalendar _getForecastRoomStatus_dtStartTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.228+08:00");
        javax.xml.datatype.XMLGregorianCalendar _getForecastRoomStatus_dtEndTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.229+08:00");
        java.lang.String _getForecastRoomStatus_sRoomType = "_getForecastRoomStatus_sRoomType-1535534947";
        javax.xml.ws.Holder<java.lang.Integer> _getForecastRoomStatus_getForecastRoomStatusResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDForecastRoomStatus> _getForecastRoomStatus_lstForecastRoomStatus = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDForecastRoomStatus>();
        port.getForecastRoomStatus(_getForecastRoomStatus_authentication, _getForecastRoomStatus_nHotelId, _getForecastRoomStatus_dtStartTime, _getForecastRoomStatus_dtEndTime, _getForecastRoomStatus_sRoomType, _getForecastRoomStatus_getForecastRoomStatusResult, _getForecastRoomStatus_lstForecastRoomStatus);

        System.out.println("getForecastRoomStatus._getForecastRoomStatus_getForecastRoomStatusResult=" + _getForecastRoomStatus_getForecastRoomStatusResult.value);
        System.out.println("getForecastRoomStatus._getForecastRoomStatus_lstForecastRoomStatus=" + _getForecastRoomStatus_lstForecastRoomStatus.value);

        }

        System.exit(0);
    }

}
