
package com.zhihui.order.partner.plateno.service.book;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2016-02-16T14:55:54.230+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class BookingSoap_BookingSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.7daysinn.cn/booking", "Booking");

    private BookingSoap_BookingSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Booking.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Booking ss = new Booking(wsdlURL, SERVICE_NAME);
        BookingSoap port = ss.getBookingSoap();  
        
        {
        System.out.println("Invoking postBookInfoWithPackage...");
        java.lang.String _postBookInfoWithPackage_sAuth = "_postBookInfoWithPackage_sAuth-1681886593";
        com.zhihui.order.partner.plateno.service.book.CRequestBookingInfo _postBookInfoWithPackage_bookingRequest = new com.zhihui.order.partner.plateno.service.book.CRequestBookingInfo();
        _postBookInfoWithPackage_bookingRequest.setRoomCount(664374770);
        _postBookInfoWithPackage_bookingRequest.setDayLength(-837229911);
        _postBookInfoWithPackage_bookingRequest.setContactor("Contactor1774073468");
        _postBookInfoWithPackage_bookingRequest.setHotelId(448116180);
        _postBookInfoWithPackage_bookingRequest.setOrganId(532815761);
        _postBookInfoWithPackage_bookingRequest.setRoomType("RoomType1084991567");
        _postBookInfoWithPackage_bookingRequest.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.244+08:00"));
        _postBookInfoWithPackage_bookingRequest.setSponsionType(-1944281058);
        _postBookInfoWithPackage_bookingRequest.setMobile("Mobile78006583");
        _postBookInfoWithPackage_bookingRequest.setRemark("Remark-914555620");
        com.zhihui.order.partner.plateno.service.book.ArrayOfDecimal _postBookInfoWithPackage_bookingRequestRoomRates = new com.zhihui.order.partner.plateno.service.book.ArrayOfDecimal();
        java.util.List<java.math.BigDecimal> _postBookInfoWithPackage_bookingRequestRoomRatesDecimal = new java.util.ArrayList<java.math.BigDecimal>();
        java.math.BigDecimal _postBookInfoWithPackage_bookingRequestRoomRatesDecimalVal1 = new java.math.BigDecimal("5653447825425773704.7106441149047425529");
        _postBookInfoWithPackage_bookingRequestRoomRatesDecimal.add(_postBookInfoWithPackage_bookingRequestRoomRatesDecimalVal1);
        _postBookInfoWithPackage_bookingRequestRoomRates.getDecimal().addAll(_postBookInfoWithPackage_bookingRequestRoomRatesDecimal);
        _postBookInfoWithPackage_bookingRequest.setRoomRates(_postBookInfoWithPackage_bookingRequestRoomRates);
        com.zhihui.order.partner.plateno.service.book.ArrayOfArrayOfDRequestBookingGuest _postBookInfoWithPackage_bookingRequestEachOrderGuests = new com.zhihui.order.partner.plateno.service.book.ArrayOfArrayOfDRequestBookingGuest();
        java.util.List<com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest> _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest>();
        com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1 = new com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest();
        java.util.List<com.zhihui.order.partner.plateno.service.book.DRequestBookingGuest> _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1DRequestBookingGuest = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.DRequestBookingGuest>();
        _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1.getDRequestBookingGuest().addAll(_postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1DRequestBookingGuest);
        _postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest.add(_postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1);
        _postBookInfoWithPackage_bookingRequestEachOrderGuests.getArrayOfDRequestBookingGuest().addAll(_postBookInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest);
        _postBookInfoWithPackage_bookingRequest.setEachOrderGuests(_postBookInfoWithPackage_bookingRequestEachOrderGuests);
        _postBookInfoWithPackage_bookingRequest.setBKMebCardNo("BKMebCardNo846611032");
        _postBookInfoWithPackage_bookingRequest.setAuthorNumber("AuthorNumber-431454146");
        com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage _postBookInfoWithPackage_arrPackage = new com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage();
        java.util.List<com.zhihui.order.partner.plateno.service.book.DConfigPackage> _postBookInfoWithPackage_arrPackageDConfigPackage = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.DConfigPackage>();
        com.zhihui.order.partner.plateno.service.book.DConfigPackage _postBookInfoWithPackage_arrPackageDConfigPackageVal1 = new com.zhihui.order.partner.plateno.service.book.DConfigPackage();
        _postBookInfoWithPackage_arrPackageDConfigPackageVal1.setQuantity(-659535637);
        _postBookInfoWithPackage_arrPackageDConfigPackageVal1.setRate(new java.math.BigDecimal("-9139741342368346223.1648410961011595988"));
        _postBookInfoWithPackage_arrPackageDConfigPackageVal1.setGoodsID(884900660);
        _postBookInfoWithPackage_arrPackageDConfigPackage.add(_postBookInfoWithPackage_arrPackageDConfigPackageVal1);
        _postBookInfoWithPackage_arrPackage.getDConfigPackage().addAll(_postBookInfoWithPackage_arrPackageDConfigPackage);
        java.math.BigDecimal _postBookInfoWithPackage_roomPrice = new java.math.BigDecimal("2758583980196438522.7184551873545467211");
        javax.xml.ws.Holder<java.lang.Integer> _postBookInfoWithPackage_postBookInfoWithPackageResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDResponseBookingResult> _postBookInfoWithPackage_bookResponse = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDResponseBookingResult>();
        port.postBookInfoWithPackage(_postBookInfoWithPackage_sAuth, _postBookInfoWithPackage_bookingRequest, _postBookInfoWithPackage_arrPackage, _postBookInfoWithPackage_roomPrice, _postBookInfoWithPackage_postBookInfoWithPackageResult, _postBookInfoWithPackage_bookResponse);

        System.out.println("postBookInfoWithPackage._postBookInfoWithPackage_postBookInfoWithPackageResult=" + _postBookInfoWithPackage_postBookInfoWithPackageResult.value);
        System.out.println("postBookInfoWithPackage._postBookInfoWithPackage_bookResponse=" + _postBookInfoWithPackage_bookResponse.value);

        }
        {
        System.out.println("Invoking isBookingAssure...");
        java.lang.String _isBookingAssure_sAuth = "_isBookingAssure_sAuth-689053109";
        java.lang.String _isBookingAssure_sCity = "_isBookingAssure_sCity-383785042";
        int _isBookingAssure_nHotelId = 1744934630;
        javax.xml.datatype.XMLGregorianCalendar _isBookingAssure_dtBegin = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.247+08:00");
        javax.xml.datatype.XMLGregorianCalendar _isBookingAssure_dtEnd = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.247+08:00");
        java.lang.String _isBookingAssure_sRoomType = "_isBookingAssure_sRoomType1085591894";
        int _isBookingAssure_nRoomNum = -46928603;
        javax.xml.ws.Holder<java.lang.Integer> _isBookingAssure_isBookingAssureResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _isBookingAssure_sMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.isBookingAssure(_isBookingAssure_sAuth, _isBookingAssure_sCity, _isBookingAssure_nHotelId, _isBookingAssure_dtBegin, _isBookingAssure_dtEnd, _isBookingAssure_sRoomType, _isBookingAssure_nRoomNum, _isBookingAssure_isBookingAssureResult, _isBookingAssure_sMsg);

        System.out.println("isBookingAssure._isBookingAssure_isBookingAssureResult=" + _isBookingAssure_isBookingAssureResult.value);
        System.out.println("isBookingAssure._isBookingAssure_sMsg=" + _isBookingAssure_sMsg.value);

        }
        {
        System.out.println("Invoking addMarketOrder...");
        java.lang.String _addMarketOrder_authentication = "_addMarketOrder_authentication1908880594";
        com.zhihui.order.partner.plateno.service.book.RequestBookingInfo _addMarketOrder_bookRequest = new com.zhihui.order.partner.plateno.service.book.RequestBookingInfo();
        _addMarketOrder_bookRequest.setHotelID(-209458281);
        _addMarketOrder_bookRequest.setRoomType("RoomType-1546116244");
        com.zhihui.order.partner.plateno.service.book.ArrayOfRoomRatePerDay _addMarketOrder_bookRequestRoomRates = new com.zhihui.order.partner.plateno.service.book.ArrayOfRoomRatePerDay();
        java.util.List<com.zhihui.order.partner.plateno.service.book.RoomRatePerDay> _addMarketOrder_bookRequestRoomRatesRoomRatePerDay = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.RoomRatePerDay>();
        com.zhihui.order.partner.plateno.service.book.RoomRatePerDay _addMarketOrder_bookRequestRoomRatesRoomRatePerDayVal1 = new com.zhihui.order.partner.plateno.service.book.RoomRatePerDay();
        _addMarketOrder_bookRequestRoomRatesRoomRatePerDayVal1.setRoomRate(new java.math.BigDecimal("5753761744431060713.6746994165837652776"));
        _addMarketOrder_bookRequestRoomRatesRoomRatePerDayVal1.setEndOfDay(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.249+08:00"));
        _addMarketOrder_bookRequestRoomRatesRoomRatePerDay.add(_addMarketOrder_bookRequestRoomRatesRoomRatePerDayVal1);
        _addMarketOrder_bookRequestRoomRates.getRoomRatePerDay().addAll(_addMarketOrder_bookRequestRoomRatesRoomRatePerDay);
        _addMarketOrder_bookRequest.setRoomRates(_addMarketOrder_bookRequestRoomRates);
        _addMarketOrder_bookRequest.setRoomCount(689148193);
        _addMarketOrder_bookRequest.setStartDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.250+08:00"));
        _addMarketOrder_bookRequest.setDayLength(1585924940);
        _addMarketOrder_bookRequest.setContactor("Contactor-1999759177");
        _addMarketOrder_bookRequest.setBKMebCardNo("BKMebCardNo1530784684");
        _addMarketOrder_bookRequest.setMobile("Mobile476097734");
        _addMarketOrder_bookRequest.setMarketActID(1804696690);
        _addMarketOrder_bookRequest.setAmount(new java.math.BigDecimal("2240159854394939668.8049907742621929329"));
        com.zhihui.order.partner.plateno.service.book.ArrayOfGuestInfo _addMarketOrder_bookRequestGuests = new com.zhihui.order.partner.plateno.service.book.ArrayOfGuestInfo();
        java.util.List<com.zhihui.order.partner.plateno.service.book.GuestInfo> _addMarketOrder_bookRequestGuestsGuestInfo = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.GuestInfo>();
        com.zhihui.order.partner.plateno.service.book.GuestInfo _addMarketOrder_bookRequestGuestsGuestInfoVal1 = new com.zhihui.order.partner.plateno.service.book.GuestInfo();
        _addMarketOrder_bookRequestGuestsGuestInfoVal1.setName("Name1020098598");
        _addMarketOrder_bookRequestGuestsGuestInfoVal1.setMobile("Mobile-1902412685");
        _addMarketOrder_bookRequestGuestsGuestInfoVal1.setRemark("Remark1494185499");
        _addMarketOrder_bookRequestGuestsGuestInfo.add(_addMarketOrder_bookRequestGuestsGuestInfoVal1);
        _addMarketOrder_bookRequestGuests.getGuestInfo().addAll(_addMarketOrder_bookRequestGuestsGuestInfo);
        _addMarketOrder_bookRequest.setGuests(_addMarketOrder_bookRequestGuests);
        _addMarketOrder_bookRequest.setRemark("Remark498288068");
        javax.xml.ws.Holder<java.lang.Integer> _addMarketOrder_addMarketOrderResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfResponseBookingInfo> _addMarketOrder_bookResponse = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfResponseBookingInfo>();
        port.addMarketOrder(_addMarketOrder_authentication, _addMarketOrder_bookRequest, _addMarketOrder_addMarketOrderResult, _addMarketOrder_bookResponse);

        System.out.println("addMarketOrder._addMarketOrder_addMarketOrderResult=" + _addMarketOrder_addMarketOrderResult.value);
        System.out.println("addMarketOrder._addMarketOrder_bookResponse=" + _addMarketOrder_bookResponse.value);

        }
        {
        System.out.println("Invoking getForecastRoomStatusFromCache...");
        java.lang.String _getForecastRoomStatusFromCache_authentication = "_getForecastRoomStatusFromCache_authentication855698936";
        int _getForecastRoomStatusFromCache_nHotelId = 1994898636;
        javax.xml.datatype.XMLGregorianCalendar _getForecastRoomStatusFromCache_dtStartTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.253+08:00");
        javax.xml.datatype.XMLGregorianCalendar _getForecastRoomStatusFromCache_dtEndTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.254+08:00");
        java.lang.String _getForecastRoomStatusFromCache_sRoomType = "_getForecastRoomStatusFromCache_sRoomType-544246878";
        javax.xml.ws.Holder<java.lang.Integer> _getForecastRoomStatusFromCache_getForecastRoomStatusFromCacheResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDForecastRoomStatus> _getForecastRoomStatusFromCache_lstForecastRoomStatus = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDForecastRoomStatus>();
        port.getForecastRoomStatusFromCache(_getForecastRoomStatusFromCache_authentication, _getForecastRoomStatusFromCache_nHotelId, _getForecastRoomStatusFromCache_dtStartTime, _getForecastRoomStatusFromCache_dtEndTime, _getForecastRoomStatusFromCache_sRoomType, _getForecastRoomStatusFromCache_getForecastRoomStatusFromCacheResult, _getForecastRoomStatusFromCache_lstForecastRoomStatus);

        System.out.println("getForecastRoomStatusFromCache._getForecastRoomStatusFromCache_getForecastRoomStatusFromCacheResult=" + _getForecastRoomStatusFromCache_getForecastRoomStatusFromCacheResult.value);
        System.out.println("getForecastRoomStatusFromCache._getForecastRoomStatusFromCache_lstForecastRoomStatus=" + _getForecastRoomStatusFromCache_lstForecastRoomStatus.value);

        }
        {
        System.out.println("Invoking getOrderNoBookingInfo...");
        java.lang.String _getOrderNoBookingInfo_authentication = "_getOrderNoBookingInfo_authentication1655224142";
        java.lang.String _getOrderNoBookingInfo_sOrderNo = "_getOrderNoBookingInfo_sOrderNo-1320757190";
        com.zhihui.order.partner.plateno.service.book.CTBookingInfo _getOrderNoBookingInfo_theBookingInfoVal = new com.zhihui.order.partner.plateno.service.book.CTBookingInfo();
        _getOrderNoBookingInfo_theBookingInfoVal.setRefund(new java.math.BigDecimal("7402233762272630680.8425275444696969466"));
        _getOrderNoBookingInfo_theBookingInfoVal.setAmout(new java.math.BigDecimal("-3831214581444267177.4307131693982400383"));
        _getOrderNoBookingInfo_theBookingInfoVal.setNAssureType(-1999775678);
        _getOrderNoBookingInfo_theBookingInfoVal.setSSellerID("SSellerID218589784");
        _getOrderNoBookingInfo_theBookingInfoVal.setSRoomNo("SRoomNo-1706793084");
        _getOrderNoBookingInfo_theBookingInfoVal.setSOrderNo("SOrderNo-1167791802");
        _getOrderNoBookingInfo_theBookingInfoVal.setNOrderSubID(871426466);
        _getOrderNoBookingInfo_theBookingInfoVal.setNHotelID(-26104124);
        _getOrderNoBookingInfo_theBookingInfoVal.setNRoomTypeID(227557753);
        _getOrderNoBookingInfo_theBookingInfoVal.setCdArrival(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.257+08:00"));
        _getOrderNoBookingInfo_theBookingInfoVal.setCdDepart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.258+08:00"));
        com.zhihui.order.partner.plateno.service.book.CTStatusType _getOrderNoBookingInfo_theBookingInfoValNStatus = com.zhihui.order.partner.plateno.service.book.CTStatusType.LEAVE;
        _getOrderNoBookingInfo_theBookingInfoVal.setNStatus(_getOrderNoBookingInfo_theBookingInfoValNStatus);
        _getOrderNoBookingInfo_theBookingInfoVal.setNOrigin("NOrigin264213370");
        _getOrderNoBookingInfo_theBookingInfoVal.setCdBookedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.258+08:00"));
        _getOrderNoBookingInfo_theBookingInfoVal.setNBookMebID(-731303093);
        _getOrderNoBookingInfo_theBookingInfoVal.setNBookPropertyID(1359750716);
        _getOrderNoBookingInfo_theBookingInfoVal.setSBookGstName("SBookGstName727441214");
        _getOrderNoBookingInfo_theBookingInfoVal.setSBookGstMoble("SBookGstMoble947408309");
        _getOrderNoBookingInfo_theBookingInfoVal.setSChkinGstName("SChkinGstName1181951541");
        _getOrderNoBookingInfo_theBookingInfoVal.setSChkinGstMobile("SChkinGstMobile-1077150603");
        _getOrderNoBookingInfo_theBookingInfoVal.setSHotelName("SHotelName-1161849403");
        _getOrderNoBookingInfo_theBookingInfoVal.setSRoomType("SRoomType1279838362");
        _getOrderNoBookingInfo_theBookingInfoVal.setSRemarks("SRemarks-1035744842");
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.CTBookingInfo> _getOrderNoBookingInfo_theBookingInfo = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.CTBookingInfo>(_getOrderNoBookingInfo_theBookingInfoVal);
        javax.xml.ws.Holder<java.lang.Integer> _getOrderNoBookingInfo_getOrderNoBookingInfoResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getOrderNoBookingInfo(_getOrderNoBookingInfo_authentication, _getOrderNoBookingInfo_sOrderNo, _getOrderNoBookingInfo_theBookingInfo, _getOrderNoBookingInfo_getOrderNoBookingInfoResult);

        System.out.println("getOrderNoBookingInfo._getOrderNoBookingInfo_theBookingInfo=" + _getOrderNoBookingInfo_theBookingInfo.value);
        System.out.println("getOrderNoBookingInfo._getOrderNoBookingInfo_getOrderNoBookingInfoResult=" + _getOrderNoBookingInfo_getOrderNoBookingInfoResult.value);

        }
        {
        System.out.println("Invoking getMarket...");
        java.lang.String _getMarket_authentication = "_getMarket_authentication-284340654";
        com.zhihui.order.partner.plateno.service.book.ArrayOfMarketActInfo _getMarket__return = port.getMarket(_getMarket_authentication);
        System.out.println("getMarket.result=" + _getMarket__return);


        }
        {
        System.out.println("Invoking queryMarketQuota...");
        java.lang.String _queryMarketQuota_authentication = "_queryMarketQuota_authentication1635753965";
        int _queryMarketQuota_hotelID = -1284640724;
        int _queryMarketQuota_marketActID = -1130644091;
        javax.xml.datatype.XMLGregorianCalendar _queryMarketQuota_beginDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.260+08:00");
        javax.xml.datatype.XMLGregorianCalendar _queryMarketQuota_endDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.261+08:00");
        com.zhihui.order.partner.plateno.service.book.ArrayOfQuota _queryMarketQuota_quotasVal = new com.zhihui.order.partner.plateno.service.book.ArrayOfQuota();
        java.util.List<com.zhihui.order.partner.plateno.service.book.Quota> _queryMarketQuota_quotasValQuota = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.Quota>();
        com.zhihui.order.partner.plateno.service.book.Quota _queryMarketQuota_quotasValQuotaVal1 = new com.zhihui.order.partner.plateno.service.book.Quota();
        _queryMarketQuota_quotasValQuotaVal1.setHotelID(419075462);
        _queryMarketQuota_quotasValQuotaVal1.setRoomType("RoomType1298276704");
        _queryMarketQuota_quotasValQuotaVal1.setRoomTypeName("RoomTypeName1556496851");
        _queryMarketQuota_quotasValQuotaVal1.setMebRoomRate(new java.math.BigDecimal("-6937850551157079148.4121144121840543685"));
        _queryMarketQuota_quotasValQuotaVal1.setDiscountRoomRate(new java.math.BigDecimal("3958200797798238796.7931082630984773253"));
        _queryMarketQuota_quotasValQuotaVal1.setMarketActID(1832038050);
        _queryMarketQuota_quotasValQuotaVal1.setCanBookFlag(true);
        _queryMarketQuota_quotasValQuotaVal1.setEndOfDay(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.262+08:00"));
        _queryMarketQuota_quotasValQuota.add(_queryMarketQuota_quotasValQuotaVal1);
        _queryMarketQuota_quotasVal.getQuota().addAll(_queryMarketQuota_quotasValQuota);
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfQuota> _queryMarketQuota_quotas = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfQuota>(_queryMarketQuota_quotasVal);
        javax.xml.ws.Holder<java.lang.Integer> _queryMarketQuota_queryMarketQuotaResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.queryMarketQuota(_queryMarketQuota_authentication, _queryMarketQuota_hotelID, _queryMarketQuota_marketActID, _queryMarketQuota_beginDate, _queryMarketQuota_endDate, _queryMarketQuota_quotas, _queryMarketQuota_queryMarketQuotaResult);

        System.out.println("queryMarketQuota._queryMarketQuota_quotas=" + _queryMarketQuota_quotas.value);
        System.out.println("queryMarketQuota._queryMarketQuota_queryMarketQuotaResult=" + _queryMarketQuota_queryMarketQuotaResult.value);

        }
        {
        System.out.println("Invoking getBookingInfoByCompose...");
        java.lang.String _getBookingInfoByCompose_authentication = "_getBookingInfoByCompose_authentication1130506914";
        com.zhihui.order.partner.plateno.service.book.ComposeSearchInfo _getBookingInfoByCompose_objCompose = new com.zhihui.order.partner.plateno.service.book.ComposeSearchInfo();
        _getBookingInfoByCompose_objCompose.setSearchTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.263+08:00"));
        com.zhihui.order.partner.plateno.service.book.CTStatusType _getBookingInfoByCompose_objComposeStatus = com.zhihui.order.partner.plateno.service.book.CTStatusType.ARRIVAL;
        _getBookingInfoByCompose_objCompose.setStatus(_getBookingInfoByCompose_objComposeStatus);
        _getBookingInfoByCompose_objCompose.setCompose(false);
        com.zhihui.order.partner.plateno.service.book.ArrayOfCTBookingInfo _getBookingInfoByCompose_arrBookingInfoVal = new com.zhihui.order.partner.plateno.service.book.ArrayOfCTBookingInfo();
        java.util.List<com.zhihui.order.partner.plateno.service.book.CTBookingInfo> _getBookingInfoByCompose_arrBookingInfoValCTBookingInfo = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.CTBookingInfo>();
        com.zhihui.order.partner.plateno.service.book.CTBookingInfo _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1 = new com.zhihui.order.partner.plateno.service.book.CTBookingInfo();
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setRefund(new java.math.BigDecimal("6267532308922224077.4074153968623566385"));
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setAmout(new java.math.BigDecimal("3966109063981453158.6649281608371990412"));
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNAssureType(-1433477869);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSSellerID("SSellerID874852335");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSRoomNo("SRoomNo-78939864");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSOrderNo("SOrderNo-748574519");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNOrderSubID(-1972399879);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNHotelID(1939421530);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNRoomTypeID(1017052380);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setCdArrival(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.264+08:00"));
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setCdDepart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.265+08:00"));
        com.zhihui.order.partner.plateno.service.book.CTStatusType _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1NStatus = com.zhihui.order.partner.plateno.service.book.CTStatusType.ARRIVAL;
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNStatus(_getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1NStatus);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNOrigin("NOrigin290634601");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setCdBookedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.265+08:00"));
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNBookMebID(1679843004);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setNBookPropertyID(-845638900);
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSBookGstName("SBookGstName-74184712");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSBookGstMoble("SBookGstMoble-455599147");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSChkinGstName("SChkinGstName-671390912");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSChkinGstMobile("SChkinGstMobile826393253");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSHotelName("SHotelName-537135873");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSRoomType("SRoomType890429217");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1.setSRemarks("SRemarks-1008829347");
        _getBookingInfoByCompose_arrBookingInfoValCTBookingInfo.add(_getBookingInfoByCompose_arrBookingInfoValCTBookingInfoVal1);
        _getBookingInfoByCompose_arrBookingInfoVal.getCTBookingInfo().addAll(_getBookingInfoByCompose_arrBookingInfoValCTBookingInfo);
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfCTBookingInfo> _getBookingInfoByCompose_arrBookingInfo = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfCTBookingInfo>(_getBookingInfoByCompose_arrBookingInfoVal);
        javax.xml.ws.Holder<java.lang.Integer> _getBookingInfoByCompose_getBookingInfoByComposeResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getBookingInfoByCompose(_getBookingInfoByCompose_authentication, _getBookingInfoByCompose_objCompose, _getBookingInfoByCompose_arrBookingInfo, _getBookingInfoByCompose_getBookingInfoByComposeResult);

        System.out.println("getBookingInfoByCompose._getBookingInfoByCompose_arrBookingInfo=" + _getBookingInfoByCompose_arrBookingInfo.value);
        System.out.println("getBookingInfoByCompose._getBookingInfoByCompose_getBookingInfoByComposeResult=" + _getBookingInfoByCompose_getBookingInfoByComposeResult.value);

        }
        {
        System.out.println("Invoking getAccTranInfo...");
        java.lang.String _getAccTranInfo_sOrderNO = "_getAccTranInfo_sOrderNO760895520";
        java.lang.String _getAccTranInfo_authentication = "_getAccTranInfo_authentication860196120";
        javax.xml.ws.Holder<java.lang.Integer> _getAccTranInfo_getAccTranInfoResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfAccTrans> _getAccTranInfo_lst = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfAccTrans>();
        port.getAccTranInfo(_getAccTranInfo_sOrderNO, _getAccTranInfo_authentication, _getAccTranInfo_getAccTranInfoResult, _getAccTranInfo_lst);

        System.out.println("getAccTranInfo._getAccTranInfo_getAccTranInfoResult=" + _getAccTranInfo_getAccTranInfoResult.value);
        System.out.println("getAccTranInfo._getAccTranInfo_lst=" + _getAccTranInfo_lst.value);

        }
        {
        System.out.println("Invoking cancelBooking...");
        java.lang.String _cancelBooking_sOrderNo = "_cancelBooking_sOrderNo-160948635";
        java.lang.String _cancelBooking_authentication = "_cancelBooking_authentication-1656659125";
        int _cancelBooking__return = port.cancelBooking(_cancelBooking_sOrderNo, _cancelBooking_authentication);
        System.out.println("cancelBooking.result=" + _cancelBooking__return);


        }
        {
        System.out.println("Invoking getHotelConstraint...");
        java.lang.String _getHotelConstraint_authentication = "_getHotelConstraint_authentication-1861350427";
        int _getHotelConstraint_nHotelId = 247687199;
        com.zhihui.order.partner.plateno.service.book.ArrayOfDateTime _getHotelConstraint_lstEndOfDayVal = new com.zhihui.order.partner.plateno.service.book.ArrayOfDateTime();
        java.util.List<javax.xml.datatype.XMLGregorianCalendar> _getHotelConstraint_lstEndOfDayValDateTime = new java.util.ArrayList<javax.xml.datatype.XMLGregorianCalendar>();
        javax.xml.datatype.XMLGregorianCalendar _getHotelConstraint_lstEndOfDayValDateTimeVal1 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.269+08:00");
        _getHotelConstraint_lstEndOfDayValDateTime.add(_getHotelConstraint_lstEndOfDayValDateTimeVal1);
        _getHotelConstraint_lstEndOfDayVal.getDateTime().addAll(_getHotelConstraint_lstEndOfDayValDateTime);
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDateTime> _getHotelConstraint_lstEndOfDay = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDateTime>(_getHotelConstraint_lstEndOfDayVal);
        javax.xml.ws.Holder<java.lang.Integer> _getHotelConstraint_getHotelConstraintResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getHotelConstraint(_getHotelConstraint_authentication, _getHotelConstraint_nHotelId, _getHotelConstraint_lstEndOfDay, _getHotelConstraint_getHotelConstraintResult);

        System.out.println("getHotelConstraint._getHotelConstraint_lstEndOfDay=" + _getHotelConstraint_lstEndOfDay.value);
        System.out.println("getHotelConstraint._getHotelConstraint_getHotelConstraintResult=" + _getHotelConstraint_getHotelConstraintResult.value);

        }
        {
        System.out.println("Invoking addAccTran...");
        java.lang.String _addAccTran_sOrderNo = "_addAccTran_sOrderNo806356465";
        java.math.BigDecimal _addAccTran_dAmount = new java.math.BigDecimal("4619155764965255918.4814834296364472175");
        java.lang.String _addAccTran_authentication = "_addAccTran_authentication1674339748";
        int _addAccTran__return = port.addAccTran(_addAccTran_sOrderNo, _addAccTran_dAmount, _addAccTran_authentication);
        System.out.println("addAccTran.result=" + _addAccTran__return);


        }
        {
        System.out.println("Invoking checkMarketOrderCondition...");
        java.lang.String _checkMarketOrderCondition_authentication = "_checkMarketOrderCondition_authentication54764971";
        com.zhihui.order.partner.plateno.service.book.EValidationType _checkMarketOrderCondition_type = com.zhihui.order.partner.plateno.service.book.EValidationType.IS_CAN_BOOK;
        java.lang.String _checkMarketOrderCondition_mebCardNo = "_checkMarketOrderCondition_mebCardNo-2071739631";
        int _checkMarketOrderCondition_marketActID = -402192179;
        int _checkMarketOrderCondition_hotelID = -38917851;
        java.lang.String _checkMarketOrderCondition_roomType = "_checkMarketOrderCondition_roomType-1382660676";
        javax.xml.datatype.XMLGregorianCalendar _checkMarketOrderCondition_beginDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.271+08:00");
        javax.xml.datatype.XMLGregorianCalendar _checkMarketOrderCondition_endDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.271+08:00");
        java.lang.String _checkMarketOrderCondition_errorMessageVal = "_checkMarketOrderCondition_errorMessageVal1396831235";
        javax.xml.ws.Holder<java.lang.String> _checkMarketOrderCondition_errorMessage = new javax.xml.ws.Holder<java.lang.String>(_checkMarketOrderCondition_errorMessageVal);
        javax.xml.ws.Holder<java.lang.Boolean> _checkMarketOrderCondition_checkMarketOrderConditionResult = new javax.xml.ws.Holder<java.lang.Boolean>();
        port.checkMarketOrderCondition(_checkMarketOrderCondition_authentication, _checkMarketOrderCondition_type, _checkMarketOrderCondition_mebCardNo, _checkMarketOrderCondition_marketActID, _checkMarketOrderCondition_hotelID, _checkMarketOrderCondition_roomType, _checkMarketOrderCondition_beginDate, _checkMarketOrderCondition_endDate, _checkMarketOrderCondition_errorMessage, _checkMarketOrderCondition_checkMarketOrderConditionResult);

        System.out.println("checkMarketOrderCondition._checkMarketOrderCondition_errorMessage=" + _checkMarketOrderCondition_errorMessage.value);
        System.out.println("checkMarketOrderCondition._checkMarketOrderCondition_checkMarketOrderConditionResult=" + _checkMarketOrderCondition_checkMarketOrderConditionResult.value);

        }
        {
        System.out.println("Invoking postReservationInfoWithPackage...");
        java.lang.String _postReservationInfoWithPackage_sAuth = "_postReservationInfoWithPackage_sAuth-808487191";
        com.zhihui.order.partner.plateno.service.book.RequestReservationInfo _postReservationInfoWithPackage_bookingRequest = new com.zhihui.order.partner.plateno.service.book.RequestReservationInfo();
        _postReservationInfoWithPackage_bookingRequest.setAmout(new java.math.BigDecimal("-2155211681847952325.9192924638185689227"));
        _postReservationInfoWithPackage_bookingRequest.setRoomCount(1392569366);
        _postReservationInfoWithPackage_bookingRequest.setDayLength(-1503093284);
        _postReservationInfoWithPackage_bookingRequest.setContactor("Contactor-975906646");
        _postReservationInfoWithPackage_bookingRequest.setHotelId(-625500503);
        _postReservationInfoWithPackage_bookingRequest.setOrganId(-640403863);
        _postReservationInfoWithPackage_bookingRequest.setRoomType("RoomType-616847289");
        _postReservationInfoWithPackage_bookingRequest.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.274+08:00"));
        _postReservationInfoWithPackage_bookingRequest.setMobile("Mobile158372795");
        _postReservationInfoWithPackage_bookingRequest.setRemark("Remark1062300068");
        com.zhihui.order.partner.plateno.service.book.ArrayOfDecimal _postReservationInfoWithPackage_bookingRequestRoomRates = new com.zhihui.order.partner.plateno.service.book.ArrayOfDecimal();
        java.util.List<java.math.BigDecimal> _postReservationInfoWithPackage_bookingRequestRoomRatesDecimal = new java.util.ArrayList<java.math.BigDecimal>();
        java.math.BigDecimal _postReservationInfoWithPackage_bookingRequestRoomRatesDecimalVal1 = new java.math.BigDecimal("-3260930245674491357.1454854839454610967");
        _postReservationInfoWithPackage_bookingRequestRoomRatesDecimal.add(_postReservationInfoWithPackage_bookingRequestRoomRatesDecimalVal1);
        _postReservationInfoWithPackage_bookingRequestRoomRates.getDecimal().addAll(_postReservationInfoWithPackage_bookingRequestRoomRatesDecimal);
        _postReservationInfoWithPackage_bookingRequest.setRoomRates(_postReservationInfoWithPackage_bookingRequestRoomRates);
        com.zhihui.order.partner.plateno.service.book.ArrayOfArrayOfDRequestBookingGuest _postReservationInfoWithPackage_bookingRequestEachOrderGuests = new com.zhihui.order.partner.plateno.service.book.ArrayOfArrayOfDRequestBookingGuest();
        java.util.List<com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest> _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest>();
        com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1 = new com.zhihui.order.partner.plateno.service.book.ArrayOfDRequestBookingGuest();
        java.util.List<com.zhihui.order.partner.plateno.service.book.DRequestBookingGuest> _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1DRequestBookingGuest = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.DRequestBookingGuest>();
        _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1.getDRequestBookingGuest().addAll(_postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1DRequestBookingGuest);
        _postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest.add(_postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuestVal1);
        _postReservationInfoWithPackage_bookingRequestEachOrderGuests.getArrayOfDRequestBookingGuest().addAll(_postReservationInfoWithPackage_bookingRequestEachOrderGuestsArrayOfDRequestBookingGuest);
        _postReservationInfoWithPackage_bookingRequest.setEachOrderGuests(_postReservationInfoWithPackage_bookingRequestEachOrderGuests);
        _postReservationInfoWithPackage_bookingRequest.setBKMebCardNo("BKMebCardNo-1311741842");
        _postReservationInfoWithPackage_bookingRequest.setAuthorNumber("AuthorNumber701982119");
        _postReservationInfoWithPackage_bookingRequest.setRatePlanCategory(-1259251253);
        com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage _postReservationInfoWithPackage_arrPackage = new com.zhihui.order.partner.plateno.service.book.ArrayOfDConfigPackage();
        java.util.List<com.zhihui.order.partner.plateno.service.book.DConfigPackage> _postReservationInfoWithPackage_arrPackageDConfigPackage = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.book.DConfigPackage>();
        com.zhihui.order.partner.plateno.service.book.DConfigPackage _postReservationInfoWithPackage_arrPackageDConfigPackageVal1 = new com.zhihui.order.partner.plateno.service.book.DConfigPackage();
        _postReservationInfoWithPackage_arrPackageDConfigPackageVal1.setQuantity(2057169930);
        _postReservationInfoWithPackage_arrPackageDConfigPackageVal1.setRate(new java.math.BigDecimal("-6228897588014382992.4646501318547634782"));
        _postReservationInfoWithPackage_arrPackageDConfigPackageVal1.setGoodsID(-760176112);
        _postReservationInfoWithPackage_arrPackageDConfigPackage.add(_postReservationInfoWithPackage_arrPackageDConfigPackageVal1);
        _postReservationInfoWithPackage_arrPackage.getDConfigPackage().addAll(_postReservationInfoWithPackage_arrPackageDConfigPackage);
        java.math.BigDecimal _postReservationInfoWithPackage_roomPrice = new java.math.BigDecimal("4012422033850025016.7493402059215104102");
        javax.xml.ws.Holder<java.lang.Integer> _postReservationInfoWithPackage_postReservationInfoWithPackageResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDResponseBookingResult> _postReservationInfoWithPackage_bookResponse = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDResponseBookingResult>();
        port.postReservationInfoWithPackage(_postReservationInfoWithPackage_sAuth, _postReservationInfoWithPackage_bookingRequest, _postReservationInfoWithPackage_arrPackage, _postReservationInfoWithPackage_roomPrice, _postReservationInfoWithPackage_postReservationInfoWithPackageResult, _postReservationInfoWithPackage_bookResponse);

        System.out.println("postReservationInfoWithPackage._postReservationInfoWithPackage_postReservationInfoWithPackageResult=" + _postReservationInfoWithPackage_postReservationInfoWithPackageResult.value);
        System.out.println("postReservationInfoWithPackage._postReservationInfoWithPackage_bookResponse=" + _postReservationInfoWithPackage_bookResponse.value);

        }
        {
        System.out.println("Invoking modifyBookingAssureType...");
        java.lang.String _modifyBookingAssureType_sOrderNo = "_modifyBookingAssureType_sOrderNo1256204024";
        java.lang.String _modifyBookingAssureType_authentication = "_modifyBookingAssureType_authentication2139431350";
        int _modifyBookingAssureType__return = port.modifyBookingAssureType(_modifyBookingAssureType_sOrderNo, _modifyBookingAssureType_authentication);
        System.out.println("modifyBookingAssureType.result=" + _modifyBookingAssureType__return);


        }
        {
        System.out.println("Invoking getForecastRoomStatus...");
        java.lang.String _getForecastRoomStatus_authentication = "_getForecastRoomStatus_authentication2009565504";
        int _getForecastRoomStatus_nHotelId = 1271075919;
        javax.xml.datatype.XMLGregorianCalendar _getForecastRoomStatus_dtStartTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.279+08:00");
        javax.xml.datatype.XMLGregorianCalendar _getForecastRoomStatus_dtEndTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-02-16T14:55:54.279+08:00");
        java.lang.String _getForecastRoomStatus_sRoomType = "_getForecastRoomStatus_sRoomType-1326389538";
        javax.xml.ws.Holder<java.lang.Integer> _getForecastRoomStatus_getForecastRoomStatusResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDForecastRoomStatus> _getForecastRoomStatus_lstForecastRoomStatus = new javax.xml.ws.Holder<com.zhihui.order.partner.plateno.service.book.ArrayOfDForecastRoomStatus>();
        port.getForecastRoomStatus(_getForecastRoomStatus_authentication, _getForecastRoomStatus_nHotelId, _getForecastRoomStatus_dtStartTime, _getForecastRoomStatus_dtEndTime, _getForecastRoomStatus_sRoomType, _getForecastRoomStatus_getForecastRoomStatusResult, _getForecastRoomStatus_lstForecastRoomStatus);

        System.out.println("getForecastRoomStatus._getForecastRoomStatus_getForecastRoomStatusResult=" + _getForecastRoomStatus_getForecastRoomStatusResult.value);
        System.out.println("getForecastRoomStatus._getForecastRoomStatus_lstForecastRoomStatus=" + _getForecastRoomStatus_lstForecastRoomStatus.value);

        }

        System.exit(0);
    }

}
