
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.zhihui.order.partner.plateno.service.login;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2016-02-16T14:15:13.722+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "AboutMember",
                      portName = "AboutMemberSoap12",
                      targetNamespace = "http://www.7daysinn.cn/booking",
                      wsdlLocation = "http://121.33.201.180:6005/AboutMember.asmx?wsdl",
                      endpointInterface = "com.zhihui.order.partner.plateno.service.login.AboutMemberSoap")
                      
public class AboutMemberSoapImpl1 implements AboutMemberSoap {

    private static final Logger LOG = Logger.getLogger(AboutMemberSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zhihui.order.partner.plateno.service.login.AboutMemberSoap#memberLogin(com.zhihui.order.partner.plateno.service.login.CTUserType  nType ,)java.lang.String  sValues ,)java.lang.String  sPassword )*
     */
    public java.lang.String memberLogin(com.zhihui.order.partner.plateno.service.login.CTUserType nType,java.lang.String sValues,java.lang.String sPassword) { 
        LOG.info("Executing operation memberLogin");
        System.out.println(nType);
        System.out.println(sValues);
        System.out.println(sPassword);
        try {
            java.lang.String _return = "_return86609151";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
