
package com.zhihui.order.partner.plateno.service.login;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2016-02-16T14:15:13.525+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class AboutMemberSoap_AboutMemberSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.7daysinn.cn/booking", "AboutMember");

    private AboutMemberSoap_AboutMemberSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AboutMember.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AboutMember ss = new AboutMember(wsdlURL, SERVICE_NAME);
        AboutMemberSoap port = ss.getAboutMemberSoap();  
        
        {
        System.out.println("Invoking memberLogin...");
        com.zhihui.order.partner.plateno.service.login.CTUserType _memberLogin_nType = com.zhihui.order.partner.plateno.service.login.CTUserType.USER_CARD;
        java.lang.String _memberLogin_sValues = "_memberLogin_sValues2123200547";
        java.lang.String _memberLogin_sPassword = "_memberLogin_sPassword-1730103162";
        java.lang.String _memberLogin__return = port.memberLogin(_memberLogin_nType, _memberLogin_sValues, _memberLogin_sPassword);
        System.out.println("memberLogin.result=" + _memberLogin__return);


        }

        System.exit(0);
    }

}
