package com.zhihui.order.partner.plateno.service.chain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2016-02-16T14:43:30.914+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://www.7daysinn.cn/booking", name = "BookingHelpSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BookingHelpSoap {

    /**
     * 根据城市获取酒店信息--2009-12-09
     */
    @RequestWrapper(localName = "GetHotelInfoByCity", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.chain.GetHotelInfoByCity")
    @WebMethod(operationName = "GetHotelInfoByCity", action = "http://www.7daysinn.cn/booking/GetHotelInfoByCity")
    @ResponseWrapper(localName = "GetHotelInfoByCityResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.chain.GetHotelInfoByCityResponse")
    public void getHotelInfoByCity(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(name = "sCity", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String sCity,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetHotelInfoByCityResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getHotelInfoByCityResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "lstHotelInfo", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfCTHotelInfo> lstHotelInfo
    );

    /**
     * 取7天已进驻的城市名称
     */
    @RequestWrapper(localName = "GetCityArray", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.chain.GetCityArray")
    @WebMethod(operationName = "GetCityArray", action = "http://www.7daysinn.cn/booking/GetCityArray")
    @ResponseWrapper(localName = "GetCityArrayResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.chain.GetCityArrayResponse")
    public void getCityArray(
        @WebParam(name = "Authentication", targetNamespace = "http://www.7daysinn.cn/booking")
        java.lang.String authentication,
        @WebParam(mode = WebParam.Mode.INOUT, name = "theCityArray", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<ArrayOfString> theCityArray,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetCityArrayResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getCityArrayResult
    );

    /**
     * 获取错误信息中文解释
     */
    @RequestWrapper(localName = "GetErrorExpression", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.chain.GetErrorExpression")
    @WebMethod(operationName = "GetErrorExpression", action = "http://www.7daysinn.cn/booking/GetErrorExpression")
    @ResponseWrapper(localName = "GetErrorExpressionResponse", targetNamespace = "http://www.7daysinn.cn/booking", className = "com.zhihui.order.partner.plateno.service.chain.GetErrorExpressionResponse")
    public void getErrorExpression(
        @WebParam(name = "nError", targetNamespace = "http://www.7daysinn.cn/booking")
        int nError,
        @WebParam(mode = WebParam.Mode.INOUT, name = "sErrMsg", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.String> sErrMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetErrorExpressionResult", targetNamespace = "http://www.7daysinn.cn/booking")
        javax.xml.ws.Holder<java.lang.Integer> getErrorExpressionResult
    );
}
