
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.zhihui.order.partner.plateno.service.chain;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2016-02-16T14:43:30.898+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "BookingHelp",
                      portName = "BookingHelpSoap",
                      targetNamespace = "http://www.7daysinn.cn/booking",
                      wsdlLocation = "http://121.33.201.180:6005/BookingHelp.asmx?wsdl",
                      endpointInterface = "com.zhihui.order.partner.plateno.service.chain.BookingHelpSoap")
                      
public class BookingHelpSoapImpl1 implements BookingHelpSoap {

    private static final Logger LOG = Logger.getLogger(BookingHelpSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zhihui.order.partner.plateno.service.chain.BookingHelpSoap#getHotelInfoByCity(java.lang.String  authentication ,)java.lang.String  sCity ,)java.lang.Integer  getHotelInfoByCityResult ,)com.zhihui.order.partner.plateno.service.chain.ArrayOfCTHotelInfo  lstHotelInfo )*
     */
    public void getHotelInfoByCity(java.lang.String authentication,java.lang.String sCity,javax.xml.ws.Holder<java.lang.Integer> getHotelInfoByCityResult,javax.xml.ws.Holder<ArrayOfCTHotelInfo> lstHotelInfo) { 
        LOG.info("Executing operation getHotelInfoByCity");
        System.out.println(authentication);
        System.out.println(sCity);
        try {
            int getHotelInfoByCityResultValue = 329110809;
            getHotelInfoByCityResult.value = getHotelInfoByCityResultValue;
            com.zhihui.order.partner.plateno.service.chain.ArrayOfCTHotelInfo lstHotelInfoValue = new com.zhihui.order.partner.plateno.service.chain.ArrayOfCTHotelInfo();
            java.util.List<com.zhihui.order.partner.plateno.service.chain.CTHotelInfo> lstHotelInfoValueCTHotelInfo = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.chain.CTHotelInfo>();
            com.zhihui.order.partner.plateno.service.chain.CTHotelInfo lstHotelInfoValueCTHotelInfoVal1 = new com.zhihui.order.partner.plateno.service.chain.CTHotelInfo();
            lstHotelInfoValueCTHotelInfoVal1.setMapURL("MapURL759978481");
            lstHotelInfoValueCTHotelInfoVal1.setForCity("ForCity-48279292");
            lstHotelInfoValueCTHotelInfoVal1.setSName("SName-2086537658");
            lstHotelInfoValueCTHotelInfoVal1.setSAddress("SAddress-58445533");
            lstHotelInfoValueCTHotelInfoVal1.setSTelephone("STelephone-1852811697");
            lstHotelInfoValueCTHotelInfoVal1.setSFaxphone("SFaxphone-1325217355");
            lstHotelInfoValueCTHotelInfoVal1.setNHotelID(836687849);
            lstHotelInfoValueCTHotelInfoVal1.setNOfficeHotelID(448728247);
            lstHotelInfoValueCTHotelInfoVal1.setNBrandID(911465898);
            com.zhihui.order.partner.plateno.service.chain.DInnInfor lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor = new com.zhihui.order.partner.plateno.service.chain.DInnInfor();
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setHotelID(-541224844);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setInnID(375477993);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setSHotelX("SHotelX460244950");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setSHotelY("SHotelY-1868230555");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setSHotelContent("SHotelContent-134709195");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setSHotelNotice("SHotelNotice654056448");
            com.zhihui.order.partner.plateno.service.chain.DInnPosition lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPosition = new com.zhihui.order.partner.plateno.service.chain.DInnPosition();
            com.zhihui.order.partner.plateno.service.chain.DDisctict lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionDisctict = new com.zhihui.order.partner.plateno.service.chain.DDisctict();
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionDisctict.setSGJCZ("SGJCZ-207600526");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionDisctict.setSHCZ("SHCZ246535524");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionDisctict.setSFJC("SFJC-1643557989");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionDisctict.setSDTZ("SDTZ-1375522154");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPosition.setDisctict(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionDisctict);
            com.zhihui.order.partner.plateno.service.chain.DArriveInn lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionArriveInn = new com.zhihui.order.partner.plateno.service.chain.DArriveInn();
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionArriveInn.setSGJCZ("SGJCZ-1022776969");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionArriveInn.setSHCZ("SHCZ2030860986");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionArriveInn.setSFJC("SFJC-58941027");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionArriveInn.setSDTZ("SDTZ-1321665894");
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPosition.setArriveInn(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPositionArriveInn);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setInnPosition(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnPosition);
            com.zhihui.order.partner.plateno.service.chain.DInnEquiment lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquiment = new com.zhihui.order.partner.plateno.service.chain.DInnEquiment();
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquiment.setBYL(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquiment.setBYB(false);
            com.zhihui.order.partner.plateno.service.chain.DInnService lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService = new com.zhihui.order.partner.plateno.service.chain.DInnService();
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService.setBDTSWJ(true);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService.setBZZCFJ(true);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService.setBZZXYJ(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService.setBZZGXJ(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService.setBYYZC(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService.setBBJBZB(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService.setBSWK(true);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquiment.setInnService(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentInnService);
            com.zhihui.order.partner.plateno.service.chain.DRoomEquiment lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment = new com.zhihui.order.partner.plateno.service.chain.DRoomEquiment();
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBMFKD(true);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBDH(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBYXDS(true);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBDLXSJ(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBLSGY(true);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBKT(true);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBDSH(true);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBDZMS(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment.setBWiFi(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquiment.setRoomEquiment(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentRoomEquiment);
            com.zhihui.order.partner.plateno.service.chain.DNearby lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearby = new com.zhihui.order.partner.plateno.service.chain.DNearby();
            com.zhihui.order.partner.plateno.service.chain.ArrayOfDPark lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearbyLstPark = new com.zhihui.order.partner.plateno.service.chain.ArrayOfDPark();
            java.util.List<com.zhihui.order.partner.plateno.service.chain.DPark> lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearbyLstParkDPark = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.chain.DPark>();
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearbyLstPark.getDPark().addAll(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearbyLstParkDPark);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearby.setLstPark(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearbyLstPark);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearby.setBIsFree(false);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquiment.setNearby(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquimentNearby);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setInnEquiment(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnEquiment);
            com.zhihui.order.partner.plateno.service.chain.ArrayOfDInnCommScore lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnCommScore = new com.zhihui.order.partner.plateno.service.chain.ArrayOfDInnCommScore();
            java.util.List<com.zhihui.order.partner.plateno.service.chain.DInnCommScore> lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnCommScoreDInnCommScore = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.chain.DInnCommScore>();
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnCommScore.getDInnCommScore().addAll(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnCommScoreDInnCommScore);
            lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor.setInnCommScore(lstHotelInfoValueCTHotelInfoVal1ObjDInnInforInnCommScore);
            lstHotelInfoValueCTHotelInfoVal1.setObjDInnInfor(lstHotelInfoValueCTHotelInfoVal1ObjDInnInfor);
            com.zhihui.order.partner.plateno.service.chain.ArrayOfDImgPath lstHotelInfoValueCTHotelInfoVal1LstDImgPath = new com.zhihui.order.partner.plateno.service.chain.ArrayOfDImgPath();
            java.util.List<com.zhihui.order.partner.plateno.service.chain.DImgPath> lstHotelInfoValueCTHotelInfoVal1LstDImgPathDImgPath = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.chain.DImgPath>();
            lstHotelInfoValueCTHotelInfoVal1LstDImgPath.getDImgPath().addAll(lstHotelInfoValueCTHotelInfoVal1LstDImgPathDImgPath);
            lstHotelInfoValueCTHotelInfoVal1.setLstDImgPath(lstHotelInfoValueCTHotelInfoVal1LstDImgPath);
            com.zhihui.order.partner.plateno.service.chain.ArrayOfQInfo lstHotelInfoValueCTHotelInfoVal1LstQInfo = new com.zhihui.order.partner.plateno.service.chain.ArrayOfQInfo();
            java.util.List<com.zhihui.order.partner.plateno.service.chain.QInfo> lstHotelInfoValueCTHotelInfoVal1LstQInfoQInfo = new java.util.ArrayList<com.zhihui.order.partner.plateno.service.chain.QInfo>();
            lstHotelInfoValueCTHotelInfoVal1LstQInfo.getQInfo().addAll(lstHotelInfoValueCTHotelInfoVal1LstQInfoQInfo);
            lstHotelInfoValueCTHotelInfoVal1.setLstQInfo(lstHotelInfoValueCTHotelInfoVal1LstQInfo);
            lstHotelInfoValueCTHotelInfo.add(lstHotelInfoValueCTHotelInfoVal1);
            lstHotelInfoValue.getCTHotelInfo().addAll(lstHotelInfoValueCTHotelInfo);
            lstHotelInfo.value = lstHotelInfoValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zhihui.order.partner.plateno.service.chain.BookingHelpSoap#getCityArray(java.lang.String  authentication ,)com.zhihui.order.partner.plateno.service.chain.ArrayOfString  theCityArray ,)java.lang.Integer  getCityArrayResult )*
     */
    public void getCityArray(java.lang.String authentication,javax.xml.ws.Holder<ArrayOfString> theCityArray,javax.xml.ws.Holder<java.lang.Integer> getCityArrayResult) { 
        LOG.info("Executing operation getCityArray");
        System.out.println(authentication);
        System.out.println(theCityArray.value);
        try {
            int getCityArrayResultValue = -341033196;
            getCityArrayResult.value = getCityArrayResultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zhihui.order.partner.plateno.service.chain.BookingHelpSoap#getErrorExpression(int  nError ,)java.lang.String  sErrMsg ,)java.lang.Integer  getErrorExpressionResult )*
     */
    public void getErrorExpression(int nError,javax.xml.ws.Holder<java.lang.String> sErrMsg,javax.xml.ws.Holder<java.lang.Integer> getErrorExpressionResult) { 
        LOG.info("Executing operation getErrorExpression");
        System.out.println(nError);
        System.out.println(sErrMsg.value);
        try {
            int getErrorExpressionResultValue = -1494038145;
            getErrorExpressionResult.value = getErrorExpressionResultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
