package com.zhihui.order.partner.plateno.service.chain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2016-02-16T14:43:30.924+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "BookingHelp", 
                  wsdlLocation = "http://121.33.201.180:6005/BookingHelp.asmx?wsdl",
                  targetNamespace = "http://www.7daysinn.cn/booking") 
public class BookingHelp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.7daysinn.cn/booking", "BookingHelp");
    public final static QName BookingHelpSoap12 = new QName("http://www.7daysinn.cn/booking", "BookingHelpSoap12");
    public final static QName BookingHelpSoap = new QName("http://www.7daysinn.cn/booking", "BookingHelpSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://121.33.201.180:6005/BookingHelp.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BookingHelp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://121.33.201.180:6005/BookingHelp.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BookingHelp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookingHelp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingHelp() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BookingHelp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BookingHelp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BookingHelp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BookingHelpSoap
     */
    @WebEndpoint(name = "BookingHelpSoap12")
    public BookingHelpSoap getBookingHelpSoap12() {
        return super.getPort(BookingHelpSoap12, BookingHelpSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingHelpSoap
     */
    @WebEndpoint(name = "BookingHelpSoap12")
    public BookingHelpSoap getBookingHelpSoap12(WebServiceFeature... features) {
        return super.getPort(BookingHelpSoap12, BookingHelpSoap.class, features);
    }
    /**
     *
     * @return
     *     returns BookingHelpSoap
     */
    @WebEndpoint(name = "BookingHelpSoap")
    public BookingHelpSoap getBookingHelpSoap() {
        return super.getPort(BookingHelpSoap, BookingHelpSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingHelpSoap
     */
    @WebEndpoint(name = "BookingHelpSoap")
    public BookingHelpSoap getBookingHelpSoap(WebServiceFeature... features) {
        return super.getPort(BookingHelpSoap, BookingHelpSoap.class, features);
    }

}
